import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'en' | 'hi' | 'es' | 'fr'

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    clients: "Clients",
    projects: "Projects",
    tasks: "Tasks",
    files: "Files",
    approvals: "Approvals",
    invoices: "Invoices",
    payments: "Payments",
    proposals: "Proposals",
    contracts: "Contracts",
    settings: "Settings",
    logout: "Log Out",
    welcome: "Welcome",
    createInvoice: "Create Invoice",
    newInvoice: "New Invoice",
    taxTemplate: "Tax Template",
    currency: "Currency",
    billingModel: "Billing Model",
    fixed: "Fixed Price",
    hourly: "Hourly Billing",
    gstr1Export: "GSTR-1 Export",
    language: "Language",
    whiteLabel: "Custom Branding",
    theme: "Theme",
    notifications: "Notifications",
    totalRevenue: "Total Revenue",
    activeProjects: "Active Projects",
    pendingApprovals: "Pending Approvals",
    overdueInvoices: "Overdue Invoices",
    recentActivity: "Recent Activity",
    search: "Search",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    view: "View",
    save: "Save",
    cancel: "Cancel",
    status: "Status",
    name: "Name",
    email: "Email",
    phone: "Phone",
    actions: "Actions",
    amount: "Amount",
    date: "Date",
    dueDate: "Due Date",
    description: "Description",
    billing: "Billing",
    total: "Total",
    tax: "Tax",
    subtotal: "Subtotal",
    discount: "Discount",
    rate: "Rate",
    quantity: "Quantity",
    priority: "Priority",
    assignee: "Assignee",
    recent: "Recent",
    settingsDesc: "Manage your agency preferences and settings",
    dashboardDesc: "Agency operations at a glance",
    clientsDesc: "Manage client relationships and portals",
    projectsDesc: "Track active milestones and scope",
    tasksDesc: "Manage project todo tasks",
    filesDesc: "Client asset storage and approvals",
    active: "Active",
    review: "Review",
    completed: "Completed",
    draft: "Draft",
    archived: "Archived",
    goodMorning: "Good morning",
    dashboardSubtitle: "Here's what's happening at Zenith Creative today.",
    editDashboard: "Edit Dashboard",
    welcomeTitle: "Welcome to ZenithOS!",
    onboardingDesc: "Get started by completing these quick steps to explore the platform.",
    dismiss: "Dismiss",
    inactive: "Inactive",
    backToClients: "Back to Clients",
    contactInformation: "Contact Information",
    gstFinancialDetails: "GST & Financial Details",
    noGstRegistered: "No GST registered",
    noPanRegistered: "No PAN registered",
    noProjectsAssigned: "No projects currently assigned to this client.",
    noInvoicesRecorded: "No invoices recorded for this client.",
    invoiceNumber: "Invoice #",
    recipientNumber: "Recipient number:",
    whatsappPlaceholder: "Type WhatsApp text alert message...",
    sending: "Sending...",
    selected: "selected",
    commaSeparated: "comma-separated",
    step: "Step",
    addClient: "Add Client",
    onboardingClientDesc: "Create your first CRM client entry.",
    defineProject: "Define a Project",
    onboardingProjectDesc: "Assign work, team, and budget.",
    issueInvoice: "Issue an Invoice",
    onboardingInvoiceDesc: "Bill client and set due dates.",
    checkClientPortal: "Check Client Portal",
    onboardingPortalDesc: "Login as client@novatech.com.",
    dashboardEditMode: "Dashboard Edit Mode",
    dashboardEditDesc: "Rearrange sections, toggle visibility, and adjust widths. Save your customizations below.",
    resetDefaults: "Reset Defaults",
    saveLayout: "Save Layout",
    totalClients: "Total Clients",
    monthlyRevenue: "Monthly Revenue",
    outstanding: "Outstanding",
    revenueOverview: "Revenue Overview",
    billedVsCollected: "Billed vs. Collected",
    billed: "Billed",
    collected: "Collected",
    threeMonths: "3 Months",
    sixMonths: "6 Months",
    twelveMonths: "12 Months",
    projectStatus: "Project Status",
    currentBreakdown: "Current breakdown",
    viewAll: "View all",
    due: "Due",
    all: "All",
    overdueInvoicesAlert: "Overdue Invoices Alert",
    overdueInvoicesTitle: "Overdue Invoices",
    overdueInvoicesDesc: "invoice(s) are past their due date.",
    noOverdueInvoices: "No overdue invoices currently.",
    sendReminder: "Send Reminder",
    reminderEmailSent: "Reminder email sent!",
    totalClientsDesc: "total",
    activeClientsDesc: "active",
    searchPlaceholderClients: "Search by name, contact, GST, tags...",
    filters: "Filters",
    listGrid: "List Grid",
    kanbanPipeline: "Kanban Pipeline",
    allStatuses: "All Statuses",
    lead: "Lead",
    industry: "Industry",
    allIndustries: "All Industries",
    technology: "Technology",
    hospitality: "Hospitality",
    fmcg: "FMCG",
    realEstate: "Real Estate",
    education: "Education",
    media: "Media",
    other: "Other",
    revenueRange: "Revenue Range",
    allRanges: "All Ranges",
    highRange: "High (≥ ₹3L)",
    mediumRange: "Medium (₹1L - ₹3L)",
    lowRange: "Low (< ₹1L)",
    sortBy: "Sort By",
    companyNameAsc: "Company Name (A-Z)",
    companyNameDesc: "Company Name (Z-A)",
    revenueDesc: "Revenue (High to Low)",
    projectsCountDesc: "Projects Count (High to Low)",
    noClientsFound: "No clients found",
    noClientsFoundDesc: "Try adjusting your filters or add a new client record.",
    exportCsv: "Export CSV",
    deleteMultipleClients: "Delete Multiple Clients?",
    deleteMultipleClientsDesc: "Are you sure you want to permanently delete these selected clients? This action is destructive and cannot be undone.",
    deleteClientTitle: "Delete Client?",
    deleteClientDesc: "Are you sure you want to permanently delete this client? This action is destructive and cannot be undone.",
    companyName: "Company Name",
    contactPerson: "Contact Person",
    address: "Address",
    notes: "Notes",
    gstin: "GSTIN",
    pan: "PAN",
    tags: "Tags",
    customMetadata: "Custom Metadata Fields",
    remove: "Remove",
    addCustomField: "+ Add Custom Field",
    createClient: "Create Client",
    clientCreatedSuccessfully: "Client created successfully.",
    clientDeletedSuccessfully: "Client deleted successfully.",
    selectedClientsDeleted: "Selected clients deleted successfully.",
    gstinCopied: "GSTIN copied to clipboard!",
    panCopied: "PAN copied to clipboard!",
    whatsappAlert: "Simulate WhatsApp Alert",
    whatsappUnavailable: "WhatsApp unavailable",
    noPhoneRegistered: "No client phone number registered.",
    sendWhatsapp: "Send WhatsApp Message",
    whatsappSent: "Simulated WhatsApp message sent",
    interactionType: "Log Call, Email, or Note",
    typeInteractionSummary: "Type communication summary...",
    saveInteraction: "Log Interaction",
    saving: "Saving...",
    interactionLogged: "Activity interaction logged successfully",
    timelineTitle: "Communications History Timeline",
    noHistory: "No communication history logged yet.",
    loggedBy: "Logged by",
    systemAuditLogs: "System Audit Logs",
    noActivity: "No activity recorded for this client.",
    establishedClient: "Established client since",
    newProject: "New Project",
    searchProjects: "Search projects...",
    budget: "Budget",
    daysOverdue: "d overdue",
    daysLeft: "d left",
    deleteProjectTitle: "Delete Project?",
    deleteProjectDesc: "Are you sure you want to permanently delete this project? This action is destructive and cannot be undone.",
    deleteMultipleProjects: "Delete Multiple Projects?",
    deleteMultipleProjectsDesc: "Are you sure you want to permanently delete these selected projects? This action is destructive and cannot be undone.",
    createProject: "Create Project",
    projectName: "Project Name",
    selectClient: "Select client...",
    assignedUser: "Assigned User",
    selectResponsibleUser: "Select responsible user...",
    startDate: "Start Date",
    deadline: "Deadline",
    defaultTaxRate: "Default Tax Rate (%)",
    defaultDiscountRate: "Default Discount Rate (%)",
    projectCreatedSuccessfully: "Project created successfully.",
    projectDeletedSuccessfully: "Project deleted successfully.",
    selectedProjectsDeleted: "Selected projects deleted successfully.",
    addTask: "Add Task",
    viewKanban: "Kanban",
    viewList: "List",
    taskPending: "Pending",
    taskInProgress: "In Progress",
    taskReview: "In Review",
    taskDone: "Done",
    noTasksInStatus: "No tasks currently in status.",
    createTask: "Create Task",
    taskTitle: "Task Title",
    selectProject: "Select project...",
    selectAssignee: "Select assignee...",
    taskCreatedSuccessfully: "Task created successfully.",
    taskStatusUpdated: "Task status updated.",
    selectedTasksDeleted: "Selected tasks deleted successfully.",
    tasksMarkedDone: "Tasks marked as completed.",
    ticking: "Ticking",
    startTracking: "Start tracking timer",
    stopTimer: "Stop timer",
    manualTimeLog: "Log manual time sheet",
    minutes: "Minutes",
    whatWork: "What did you work on?",
    logTimeSheet: "Log Time Sheet Record",
    timeHistory: "Time sheet history logs",
    noTimeHistory: "No time tracking logs saved for this task yet.",
    sessionSummary: "Session Summary",
    stopAndLog: "Stop & Log",
    uploadFiles: "Upload Files",
    dragDropFiles: "Drag & drop files here",
    orBrowse: "or browse to upload",
    fileTypesSupported: "All file types supported (Max 100MB)",
    searchFiles: "Search files...",
    fileDetails: "File Details",
    fileType: "Type",
    fileSize: "Size",
    uploadedBy: "Uploaded By",
    openMetadata: "Open Metadata Page",
    editFile: "Edit File",
    project: "Project",
    fileSelect: "File",
    renameFile: "Rename File (Optional)",
    descriptionOptional: "Description (Optional)",
    fileConflict: "File with this name already exists.",
    uploadAsNewVersion: "Upload as new version (increment version)",
    overwriteExisting: "Overwrite/replace existing file entry",
    upload: "Upload",
    fileUploadedSuccessfully: "File uploaded successfully.",
    fileDeletedSuccessfully: "File deleted successfully.",
    deleteFileTitle: "Delete File?",
    deleteFileDesc: "Are you sure you want to permanently delete this file? This action is destructive and cannot be undone.",
    exportGstr1: "Export GSTR-1",
    allInvoices: "All Invoices",
    recurringSubscriptions: "Recurring Subscriptions",
    totalBilled: "Total Billed",
    choosePaymentMethod: "Choose payment method",
    securingRazorpay: "Secured by Razorpay (Mock Mode)",
    downloadPdf: "Download PDF",
    gstr1Downloaded: "GSTR-1 report downloaded successfully.",
    invoiceSent: "Invoice sent successfully.",
    paymentSuccessful: "Payment Successful!",
    paymentProcessing: "Processing payment...",
    paymentProcessingDesc: "Communicating with payment servers.",
    runTemplate: "Trigger Run",
    subscriptionTemplateCreated: "Recurring subscription template created successfully.",
    subscriptionTemplateDeleted: "Recurring template deleted.",
    invoiceGeneratedFromTemplate: "Invoice generated successfully from this template!",
    myPortal: "My Portal",
    sharedFiles: "Shared Files",
    myInvoices: "My Invoices",
    myProjects: "My Projects",
    history: "History",
    allCaughtUp: "All caught up! No approvals pending.",
    requestChanges: "Request Changes",
    feedbackLabel: "Client Feedback",
    digitallySigned: "Digitally Signed & Verified",
    timestamp: "Timestamp",
    respondToApproval: "Respond to Approval",
    approveAndSign: "Approve & Sign",
    eSignatureVerification: "E-Signature Verification",
    typeSignature: "Type Signature",
    sealStamp: "Seal Stamp",
    typeName: "Type Full Name",
    signatureStyle: "Signature Style",
    consentText: "I agree that this signature is a valid, legally binding representation of my approval, electronic signature and consent.",
    whyRevisionsNeeded: "Why are revisions needed?",
    submitRevisionRequest: "Submit Revision Request",
    assetApprovedAndSigned: "Asset approved and signed successfully.",
    revisionRequested: "Revision requested.",
    filesAcrossProjects: "files across all projects",
    pleaseSelectFileAndProject: "Please select a file and a project to upload.",
    fileRenamedSuccessfully: "File renamed successfully.",
    file: "File",
    version: "Version",
    downloads: "Downloads",
    download: "Download",
    noFilesFound: "No files found",
    noFilesFoundDesc: "Upload your first file or adjust your search.",
    leaveEmptyOriginalName: "Leave empty to use original name",
    addBriefDescription: "Add a brief description of the file...",
    fileMetadata: "File Metadata",
    fileNotFound: "File Not Found",
    fileNotFoundDesc: "The requested file could not be found or has been deleted.",
    fileMetadataDesc: "Detailed Read-Only File Metadata & Parameters",
    properties: "Properties",
    uploadDate: "Upload Date",
    projectReference: "Project Reference",
    downloadFileRaw: "Download file raw",
    noDescriptionProvided: "No description provided for this file.",
    storageKey: "Storage Key",
    backToFiles: "Back to Files",
    recurringInvoices: "Recurring Invoices",
    invoicesCount: "invoices",
    recurringActiveCount: "recurring subscriptions active",
    awaitingPayment: "Awaiting Payment",
    transactionHistory: "Transaction History",
    noTransactionsYet: "No transactions yet.",
    transaction: "Transaction",
    method: "Method",
    completePayment: "Complete Payment",
    paying: "Paying",
    pleaseWaitDoNotClose: "Please wait, do not close this window.",
    paymentReceiptGenerated: "A mock receipt has been generated.",
    done: "Done",
    createSubscriptionTemplate: "Create Subscription Template",
    billingFrequency: "Billing Frequency",
    firstBillingDate: "First Billing Date",
    gstTaxRate: "GST Tax Rate (%)",
    discountType: "Discount Type",
    discountValue: "Discount Value",
    lineItems: "Line Items",
    addItem: "+ Add Item",
    notesPrintedInvoice: "Notes (printed on generated invoice)",
    notesPlaceholderSubscription: "e.g. Subscriptions terms, billing info...",
    pricingCalculationsPreview: "Pricing calculations preview",
    totalAmount: "Total Amount",
    saveTemplate: "Save Template",
    weekly: "Weekly",
    monthly: "Monthly",
    quarterly: "Quarterly",
    percentage: "Percentage (%)",
    flatAmount: "Flat Amount",
    accountHolder: "Account Holder",
    bankName: "Bank Name",
    accountNumber: "Account Number",
    ifscCode: "IFSC Code",
    upiId: "UPI ID",
    scanToPayUPI: "Scan to Pay via UPI",
    scanUsingUpiApps: "Scan using BHIM, GPay, PhonePe, or Paytm",
    pay: "Pay",
    close: "Close",
    stripeCardCheckout: "Stripe Card Checkout",
    stripeDesc: "Visa, Mastercard, AMEX, Apple Pay",
    paypalCheckout: "PayPal Checkout",
    paypalDesc: "Pay via PayPal balance or account",
    wiseTransfer: "Wise Direct Transfer",
    wiseDesc: "Simulate direct international bank wire",
    upiDesc: "Google Pay, PhonePe, Paytm",
    cardDesc: "Visa, Mastercard, RuPay",
    netbankingDesc: "All major banks",
    creditDebitCard: "Credit / Debit Card",
    netBanking: "Net Banking",
    payNow: "Pay Now",
    sendInvoice: "Send Invoice",
    taxRate: "Tax rate",
    zeroRatedGst: "Zero-rated GST",
    cgst: "CGST",
    sgst: "SGST",
    igst: "IGST",
    rcmWarning: "GST payable under Reverse Charge (RCM). Tax is NOT added to the invoice total.",
    roundingOff: "Rounding Off",
    totalExclGst: "Total (Excl. GST)",
    totalInvoiceValue: "Total Invoice Value",
    tdsWithheld: "TDS Withheld",
    netPayableDue: "Net Payable / Due",
    bankTransferDetails: "Bank Transfer Details",
    placeOfSupply: "Place of Supply",
    dateFilter: "Date",
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    thisYear: "This Year",
    customRange: "Custom Range",
    from: "from",
    to: "to",
    overdue: "Overdue",
    sent: "Sent",
    paid: "Paid",
    agencyProfile: "Agency Profile",
    emailSettings: "Email Settings",
    notificationPreferences: "Notification Preferences",
    securitySettings: "Security Settings",
    brandingConfiguration: "Branding Configuration",
    settingsDescZenithOS: "Manage your ZenithOS configuration",
    companyLogo: "Company Logo",
    agencyName: "Agency Name",
    website: "Website",
    contactEmail: "Contact Email",
    gstNumber: "GST Number",
    saveChanges: "Save Changes",
    emailProvider: "Email Provider",
    poweredBy: "Powered by",
    senderName: "Sender Name",
    senderEmail: "Sender Email",
    automatedEmails: "Automated Emails",
    welcomeEmailClient: "Welcome email on client creation",
    approvalRequestNotif: "Approval request notifications",
    invoiceDeliveryEmails: "Invoice delivery emails",
    paymentReceiptEmails: "Payment receipt emails",
    deadlineReminders: "Deadline reminders",
    saveSettings: "Save Settings",
    newClientAdded: "New client added",
    newClientAddedDesc: "When a new client is created",
    projectAssignedYou: "Project assigned to you",
    projectAssignedYouDesc: "When you are added to a project",
    approvalReceived: "Approval received",
    approvalReceivedDesc: "When a client responds to an approval request",
    paymentReceived: "Payment received",
    paymentReceivedDesc: "When an invoice is paid",
    deadlineApproaching: "Deadline approaching",
    deadlineApproachingDesc: "3 days before a project deadline",
    invoiceOverdue: "Invoice overdue",
    invoiceOverdueDesc: "When an invoice passes its due date",
    savePreferences: "Save Preferences",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    sessionManagement: "Session Management",
    sessionManagementDesc: "JWT tokens expire after 7 days. Refresh tokens are valid for 30 days.",
    loggedOutInactivity: "You have been logged out due to inactivity.",
    updatePassword: "Update Password",
    agencyBrandName: "Agency/Brand Name",
    brandAccentTheme: "Brand Accent Theme",
    brandLogoUrl: "Brand Logo URL",
    invoiceFooterText: "Invoice Footer Text",
    saveBranding: "Save Branding",
    orangeDefault: "Orange (Default)",
    blueAccent: "Blue",
    emeraldAccent: "Emerald",
    indigoAccent: "Indigo",
    violetAccent: "Violet",
    welcomeBack: "Welcome back",
    approvalsWaiting: "approvals waiting",
    invoicesOutstanding: "invoice(s) outstanding",
    completedTasksOf: "tasks done",
    pending: "Pending",
    signatureStylePreview: "Preview style",
    liveSignaturePreview: "Live Signature Preview",
    initialsPlaceholder: "Initials (max 3 letters)",
    liveStampPreview: "Live Stamp Preview",
    commentNoteOptional: "Comment/Note (optional)",
    addCommentNotePlaceholder: "Add a comment or note...",
    goBack: "Go Back",
    signApprove: "Sign & Approve",
    specifyRevisionsRequired: "Specify exactly what changes are required...",
    noInvoices: "No Invoices",
    noInvoicesFoundAccount: "No invoices found for your account.",
    createFirstInvoice: "Create your first invoice to send to clients.",
    client: "Client",
    inclTax: "incl. tax",
    nextBillingDate: "Next Billing Date",
    invoiceDetails: "Invoice Details",
    taxableValue: "Taxable Value",
    orderId: "Order ID",
    paymentReceivedSuccess: "received successfully.",
    transactionsRecorded: "transactions recorded",
    totalCollected: "Total Collected",
    pendingInvoices: "Pending Invoices",
    failed: "Failed",
    partial: "Partial",
    received: "received",
    inApp: "In-app",
    security: "Security",
    clientPortalWelcomeMessage: "Client Portal Welcome Message",
    brandingSaved: "Branding configurations saved and applied successfully!",
    youHave: "You have",
    and: "and",
    of: "of",
    approve: "Approve",
    noCompletedApprovalsYet: "No completed approvals yet.",
    noSharedFiles: "No files shared with you yet.",
    action: "Action",
    receipt: "Receipt",
    pdfSimulated: "PDF generation is simulated for this environment.",
    assetForReview: "Asset for Review",
    selectResponseChoice: "Please select your response choice below:",
    simulatePayment: "Simulate Payment",
    hsnSac: "HSN/SAC",
    qty: "Qty",
    flat: "Flat",
    lutNo: "LUT No",
    invoice: "Invoice",
    agreeToTermsError: "You must agree to the legally binding terms.",
    typeSignatureError: "Please type your name for the signature.",
    stampInitialsError: "Please enter your initials for the stamp seal."
  },
  hi: {
    dashboard: "डैशबोर्ड",
    clients: "ग्राहक",
    projects: "परियोजनाएं",
    tasks: "कार्य",
    files: "फ़ाइलें",
    approvals: "स्वीकृतियाँ",
    invoices: "चालान",
    payments: "भुगतान",
    proposals: "प्रस्ताव",
    contracts: "अनुबंध",
    settings: "सेटिंग्स",
    logout: "लॉग आउट",
    welcome: "स्वागत हे",
    createInvoice: "चालान बनाएं",
    newInvoice: "नया चालान",
    taxTemplate: "कर टेम्पलेट",
    currency: "मुद्रा",
    billingModel: "बिलिंग मॉडल",
    fixed: "निश्चित मूल्य",
    hourly: "प्रति घंटा बिलिंग",
    gstr1Export: "जीएसटीआर-1 निर्यात",
    language: "भाषा",
    whiteLabel: "कस्टम ब्रांडिंग",
    theme: "थीम",
    notifications: "सूचनाएं",
    totalRevenue: "कुल राजस्व",
    activeProjects: "सक्रिय परियोजनाएं",
    pendingApprovals: "लंबित स्वीकृतियाँ",
    overdueInvoices: "देय चालान",
    recentActivity: "हाल की गतिविधि",
    search: "खोजें",
    add: "जोड़ें",
    edit: "संपादित करें",
    delete: "हटाएं",
    view: "देखें",
    save: "सुरक्षित करें",
    cancel: "रद्द करें",
    status: "स्थिति",
    name: "नाम",
    email: "ईमेल",
    phone: "फ़ोन",
    actions: "कार्रवाई",
    amount: "राशि",
    date: "तारीख",
    dueDate: "देय तिथि",
    description: "विवरण",
    billing: "बिलिंग",
    total: "कुल",
    tax: "कर",
    subtotal: "उप-योग",
    discount: "छूट",
    rate: "दर",
    quantity: "मात्रा",
    priority: "प्राथमिकता",
    assignee: "सौंपा गया",
    recent: "हालिया",
    settingsDesc: "अपनी एजेंसी की प्राथमिकताओं और सेटिंग्स को प्रबंधित करें",
    dashboardDesc: "एजेंसी संचालन एक नज़र में",
    clientsDesc: "ग्राहक संबंधों और पोर्टल्स को प्रबंधित करें",
    projectsDesc: "सक्रिय मील के पत्थर और दायरे को ट्रैक करें",
    tasksDesc: "प्रोजेक्ट टूडू कार्यों को प्रबंधित करें",
    filesDesc: "ग्राहक संपत्ति भंडारण और अनुमोदन",
    active: "सक्रिय",
    review: "समीक्षा",
    completed: "पूर्ण",
    draft: "प्रारूप",
    archived: "संग्रहीत",
    goodMorning: "शुभ प्रभात",
    dashboardSubtitle: "आज Zenith Creative में क्या हो रहा है, यहाँ देखें।",
    editDashboard: "डैशबोर्ड संपादित करें",
    welcomeTitle: "ZenithOS में आपका स्वागत है!",
    onboardingDesc: "प्लेटफ़ॉर्म का पता लगाने के लिए इन त्वरित चरणों को पूरा करके शुरुआत करें।",
    dismiss: "खारिज करें",
    inactive: "निष्क्रिय",
    backToClients: "ग्राहकों पर वापस जाएं",
    contactInformation: "संपर्क जानकारी",
    gstFinancialDetails: "जीएसटी और वित्तीय विवरण",
    noGstRegistered: "कोई जीएसटी पंजीकृत नहीं है",
    noPanRegistered: "कोई पैन पंजीकृत नहीं है",
    noProjectsAssigned: "इस ग्राहक को वर्तमान में कोई परियोजना नहीं सौंपी गई है।",
    noInvoicesRecorded: "इस ग्राहक के लिए कोई चालान दर्ज नहीं किया गया है।",
    invoiceNumber: "चालान संख्या",
    recipientNumber: "प्राप्तकर्ता संख्या:",
    whatsappPlaceholder: "व्हाट्सएप टेक्स्ट अलर्ट संदेश टाइप करें...",
    sending: "भेज रहा है...",
    selected: "चयनित",
    commaSeparated: "अल्पविराम से अलग",
    step: "चरण",
    addClient: "ग्राहक जोड़ें",
    onboardingClientDesc: "अपना पहला CRM ग्राहक प्रविष्टि बनाएं।",
    defineProject: "परियोजना परिभाषित करें",
    onboardingProjectDesc: "कार्य, टीम और बजट सौंपें।",
    issueInvoice: "चालान जारी करें",
    onboardingInvoiceDesc: "ग्राहक को बिल भेजें और देय तिथियां निर्धारित करें।",
    checkClientPortal: "ग्राहक पोर्टल देखें",
    onboardingPortalDesc: "client@novatech.com के रूप में लॉग इन करें।",
    dashboardEditMode: "डैशबोर्ड संपादन मोड",
    dashboardEditDesc: "अनुभागों को पुनर्व्यवस्थित करें, दृश्यता टॉगल करें, और चौड़ाई समायोजित करें। नीचे अपने कस्टमाइज़ेशन सहेजें।",
    resetDefaults: "डिफ़ॉल्ट रीसेट करें",
    saveLayout: "लेआउट सुरक्षित करें",
    totalClients: "कुल ग्राहक",
    monthlyRevenue: "मासिक राजस्व",
    outstanding: "बकाया",
    revenueOverview: "राजस्व विवरण",
    billedVsCollected: "बिल बनाम संकलित",
    billed: "बिल भेजा गया",
    collected: "संकलित",
    threeMonths: "3 महीने",
    sixMonths: "6 महीने",
    twelveMonths: "12 महीने",
    projectStatus: "परियोजना स्थिति",
    currentBreakdown: "वर्तमान विवरण",
    viewAll: "सभी देखें",
    due: "देय",
    all: "सभी",
    overdueInvoicesAlert: "देय चालान अलर्ट",
    overdueInvoicesTitle: "देय चालान",
    overdueInvoicesDesc: "चालान अपनी देय तिथि पार कर चुके हैं।",
    noOverdueInvoices: "वर्तमान में कोई देय चालान नहीं है।",
    sendReminder: "अनुस्मारक भेजें",
    reminderEmailSent: "अनुस्मारक ईमेल सफलतापूर्वक भेजा गया!",
    totalClientsDesc: "कुल",
    activeClientsDesc: "सक्रिय",
    searchPlaceholderClients: "नाम, संपर्क, जीएसटी, टैग द्वारा खोजें...",
    filters: "फ़िल्टर",
    listGrid: "सूची ग्रिड",
    kanbanPipeline: "कानबन पाइपलाइन",
    allStatuses: "सभी स्थितियां",
    lead: "लीड",
    industry: "उद्योग",
    allIndustries: "सभी उद्योग",
    technology: "तकनीकी",
    hospitality: "आतिथ्य",
    fmcg: "FMCG",
    realEstate: "रियल एस्टेट",
    education: "शिक्षा",
    media: "मीडिया",
    other: "अन्य",
    revenueRange: "राजस्व सीमा",
    allRanges: "सभी सीमाएं",
    highRange: "उच्च (≥ ₹3L)",
    mediumRange: "मध्यम (₹1L - ₹3L)",
    lowRange: "कम (< ₹1L)",
    sortBy: "द्वारा क्रमबद्ध करें",
    companyNameAsc: "कंपनी का नाम (A-Z)",
    companyNameDesc: "कंपनी का नाम (Z-A)",
    revenueDesc: "राजस्व (उच्च से कम)",
    projectsCountDesc: "परियोजनाओं की संख्या (उच्च से कम)",
    noClientsFound: "कोई ग्राहक नहीं मिला",
    noClientsFoundDesc: "अपने फ़िल्टर समायोजित करने का प्रयास करें या एक नया ग्राहक रिकॉर्ड जोड़ें।",
    exportCsv: "सीएसवी निर्यात करें",
    deleteMultipleClients: "एकाधिक ग्राहक हटाएं?",
    deleteMultipleClientsDesc: "क्या आप वाकई इन चयनित ग्राहकों को स्थायी रूप से हटाना चाहते हैं? यह कार्रवाई विनाशकारी है और इसे पूर्ववत नहीं किया जा सकता है।",
    deleteClientTitle: "ग्राहक हटाएं?",
    deleteClientDesc: "क्या आप वाकई इस ग्राहक को स्थायी रूप से हटाना चाहते हैं? यह कार्रवाई विनाशकारी है और इसे पूर्ववत नहीं किया जा सकता है।",
    companyName: "कंपनी का नाम",
    contactPerson: "संपर्क व्यक्ति",
    address: "पता",
    notes: "टिप्पणियाँ",
    gstin: "जीएसटीआईएन",
    pan: "पैन",
    tags: "टैग",
    customMetadata: "कस्टम मेटाडेटा फ़ील्ड",
    remove: "हटाएं",
    addCustomField: "+ कस्टम फ़ील्ड जोड़ें",
    createClient: "ग्राहक बनाएं",
    clientCreatedSuccessfully: "ग्राहक सफलतापूर्वक बनाया गया।",
    clientDeletedSuccessfully: "ग्राहक सफलतापूर्वक हटाया गया।",
    selectedClientsDeleted: "चयनित ग्राहक सफलतापूर्वक हटाए गए।",
    gstinCopied: "जीएसटीआईएन क्लिपबोर्ड पर कॉपी किया गया!",
    panCopied: "पैन क्लिपबोर्ड पर कॉपी किया गया!",
    whatsappAlert: "व्हाट्सएप अलर्ट अनुकरण करें",
    whatsappUnavailable: "व्हाट्सएप अनुपलब्ध",
    noPhoneRegistered: "कोई ग्राहक फ़ोन नंबर पंजीकृत नहीं है।",
    sendWhatsapp: "व्हाट्सएप संदेश भेजें",
    whatsappSent: "व्हाट्सएप संदेश भेजा गया",
    interactionType: "कॉल, ईमेल या नोट दर्ज करें",
    typeInteractionSummary: "संचार सारांश टाइप करें...",
    saveInteraction: "इंटरैक्शन दर्ज करें",
    saving: "सहेज रहा है...",
    interactionLogged: "गतिविधि इंटरैक्शन सफलतापूर्वक दर्ज की गई",
    timelineTitle: "संचार इतिहास समयरेखा",
    noHistory: "अभी तक कोई संचार इतिहास दर्ज नहीं किया गया है।",
    loggedBy: "द्वारा दर्ज किया गया",
    systemAuditLogs: "सिस्टम ऑडिट लॉग",
    noActivity: "इस ग्राहक के लिए कोई गतिविधि दर्ज नहीं की गई है।",
    establishedClient: "स्थापित ग्राहक तब से",
    newProject: "नई परियोजना",
    searchProjects: "परियोजनाएं खोजें...",
    budget: "बजट",
    daysOverdue: "दिन देय बीत चुके हैं",
    daysLeft: "दिन शेष",
    deleteProjectTitle: "परियोजना हटाएं?",
    deleteProjectDesc: "क्या आप वाकई इस परियोजना को स्थायी रूप से हटाना चाहते हैं? यह कार्रवाई विनाशकारी है और इसे पूर्ववत नहीं किया जा सकता है।",
    deleteMultipleProjects: "एकाधिक परियोजनाएं हटाएं?",
    deleteMultipleProjectsDesc: "क्या आप वाकई इन चयनित परियोजनाओं को स्थायी रूप से हटाना चाहते हैं? यह कार्रवाई विनाशकारी है और इसे पूर्ववत नहीं किया जा सकता है।",
    createProject: "परियोजना बनाएं",
    projectName: "परियोजना का नाम",
    selectClient: "ग्राहक चुनें...",
    assignedUser: "सौंपा गया उपयोगकर्ता",
    selectResponsibleUser: "जिम्मेदार उपयोगकर्ता चुनें...",
    startDate: "प्रारंभ तिथि",
    deadline: "समय सीमा",
    defaultTaxRate: "डिफ़ॉल्ट कर दर (%)",
    defaultDiscountRate: "डिफ़ॉल्ट छूट दर (%)",
    projectCreatedSuccessfully: "परियोजना सफलतापूर्वक बनाई गई।",
    projectDeletedSuccessfully: "परियोजना सफलतापूर्वक हटाई गई।",
    selectedProjectsDeleted: "चयनित परियोजनाएं सफलतापूर्वक हटाई गईं।",
    addTask: "कार्य जोड़ें",
    viewKanban: "कानबन",
    viewList: "सूची",
    taskPending: "लंबित",
    taskInProgress: "सक्रिय",
    taskReview: "समीक्षा में",
    taskDone: "पूर्ण",
    noTasksInStatus: "इस स्थिति में वर्तमान में कोई कार्य नहीं है।",
    createTask: "कार्य बनाएं",
    taskTitle: "कार्य का शीर्षक",
    selectProject: "परियोजना चुनें...",
    selectAssignee: "सौंपा गया व्यक्ति चुनें...",
    taskCreatedSuccessfully: "कार्य सफलतापूर्वक बनाया गया।",
    taskStatusUpdated: "कार्य की स्थिति अपडेट की गई।",
    selectedTasksDeleted: "चयनित कार्य सफलतापूर्वक हटाए गए।",
    tasksMarkedDone: "कार्यों को पूर्ण के रूप में चिह्नित किया गया।",
    ticking: "टिकिंग",
    startTracking: "ट्रैकिंग टाइमर प्रारंभ करें",
    stopTimer: "टाइमर रोकें",
    manualTimeLog: "मैनुअल टाइम शीट दर्ज करें",
    minutes: "मिनट",
    whatWork: "आपने किस पर काम किया?",
    logTimeSheet: "टाइम शीट रिकॉर्ड दर्ज करें",
    timeHistory: "टाइम शीट इतिहास लॉग",
    noTimeHistory: "इस कार्य के लिए अभी तक कोई टाइम ट्रैकिंग लॉग सहेजा नहीं गया है।",
    sessionSummary: "सत्र सारांश",
    stopAndLog: "रोकें और दर्ज करें",
    uploadFiles: "फ़ाइलें अपलोड करें",
    dragDropFiles: "फ़ाइलों को यहाँ खींचें और छोड़ें",
    orBrowse: "या अपलोड करने के लिए ब्राउज़ करें",
    fileTypesSupported: "सभी फ़ाइल प्रकार समर्थित हैं (अधिकतम 100MB)",
    searchFiles: "फ़ाइलें खोजें...",
    fileDetails: "फ़ाइल विवरण",
    fileType: "प्रकार",
    fileSize: "आकार",
    uploadedBy: "द्वारा अपलोड किया गया",
    openMetadata: "मेटाडेटा पृष्ठ खोलें",
    editFile: "फ़ाइल संपादित करें",
    project: "परियोजना",
    fileSelect: "फ़ाइल",
    renameFile: "फ़ाइल का नाम बदलें (वैकल्पिक)",
    descriptionOptional: "विवरण (वैकल्पिक)",
    fileConflict: "इस नाम की फ़ाइल पहले से मौजूद है।",
    uploadAsNewVersion: "नए संस्करण के रूप में अपलोड करें (संस्करण बढ़ाएं)",
    overwriteExisting: "मौजूदा फ़ाइल प्रविष्टि को अधिलेखित/बदलें",
    upload: "अपलोड करें",
    fileUploadedSuccessfully: "फ़ाइल सफलतापूर्वक अपलोड की गई।",
    fileDeletedSuccessfully: "फ़ाइल सफलतापूर्वक हटाई गई।",
    deleteFileTitle: "फ़ाइल हटाएं?",
    deleteFileDesc: "क्या आप वाकई इस फ़ाइल को स्थायी रूप से हटाना चाहते हैं? यह कार्रवाई विनाशकारी है और इसे पूर्ववत नहीं किया जा सकता है।",
    exportGstr1: "जीएसटीआर-1 निर्यात करें",
    allInvoices: "सभी चालान",
    recurringSubscriptions: "आवर्ती सदस्यताएं",
    totalBilled: "कुल बिल",
    choosePaymentMethod: "भुगतान विधि चुनें",
    securingRazorpay: "रैज़रपे द्वारा सुरक्षित (मॉक मोड)",
    downloadPdf: "पीडीएफ डाउनलोड करें",
    gstr1Downloaded: "जीएसटीआर-1 रिपोर्ट सफलतापूर्वक डाउनलोड की गई।",
    invoiceSent: "चालान सफलतापूर्वक भेजा गया।",
    paymentSuccessful: "भुगतान सफल!",
    paymentProcessing: "भुगतान संसाधित हो रहा है...",
    paymentProcessingDesc: "भुगतान सर्वर के साथ संचार हो रहा है।",
    runTemplate: "रन ट्रिगर करें",
    subscriptionTemplateCreated: "आवर्ती सदस्यता टेम्पलेट सफलतापूर्वक बनाया गया।",
    subscriptionTemplateDeleted: "आवर्ती टेम्पलेट हटाया गया।",
    invoiceGeneratedFromTemplate: "इस टेम्पलेट से चालान सफलतापूर्वक जनरेट किया गया!",
    myPortal: "मेरा पोर्टल",
    sharedFiles: "साझा की गई फ़ाइलें",
    myInvoices: "मेरे चालान",
    myProjects: "मेरी परियोजनाएं",
    history: "इतिहास",
    allCaughtUp: "सब ठीक है! कोई स्वीकृति लंबित नहीं है।",
    requestChanges: "परिवर्तन का अनुरोध करें",
    feedbackLabel: "ग्राहक प्रतिक्रिया",
    digitallySigned: "डिजिटल रूप से हस्ताक्षरित और सत्यापित",
    timestamp: "समय stamp",
    respondToApproval: "स्वीकृति पर प्रतिक्रिया दें",
    approveAndSign: "स्वीकृत करें और हस्ताक्षर करें",
    eSignatureVerification: "ई-हस्ताक्षर सत्यापन",
    typeSignature: "हस्ताक्षर टाइप करें",
    sealStamp: "सील स्टैम्प",
    typeName: "पूरा नाम टाइप करें",
    signatureStyle: "हस्ताक्षर शैली",
    consentText: "मैं सहमत हूँ कि यह हस्ताक्षर मेरी स्वीकृति, इलेक्ट्रॉनिक हस्ताक्षर और सहमति का एक वैध, कानूनी रूप से बाध्यकारी प्रतिनिधित्व है।",
    whyRevisionsNeeded: "संशोधन की आवश्यकता क्यों है?",
    submitRevisionRequest: "संशोधन अनुरोध सबमिट करें",
    assetApprovedAndSigned: "संपत्ति सफलतापूर्वक स्वीकृत और हस्ताक्षरित की गई।",
    revisionRequested: "संशोधन का अनुरोध किया गया।",
    filesAcrossProjects: "सभी परियोजनाओं में फ़ाइलें",
    pleaseSelectFileAndProject: "कृपया अपलोड करने के लिए एक फ़ाइल और एक परियोजना चुनें।",
    fileRenamedSuccessfully: "फ़ाइल का नाम सफलतापूर्वक बदला गया।",
    file: "फ़ाइल",
    version: "संस्करण",
    downloads: "डाउनलोड",
    download: "डाउनलोड",
    noFilesFound: "कोई फ़ाइल नहीं मिली",
    noFilesFoundDesc: "अपनी पहली फ़ाइल अपलोड करें या अपनी खोज को समायोजित करें।",
    leaveEmptyOriginalName: "मूल नाम का उपयोग करने के लिए खाली छोड़ें",
    addBriefDescription: "फ़ाइल का संक्षिप्त विवरण जोड़ें...",
    fileMetadata: "फ़ाइल मेटाडेटा",
    fileNotFound: "फ़ाइल नहीं मिली",
    fileNotFoundDesc: "अनुरोधित फ़ाइल नहीं मिल सकी या हटा दी गई है।",
    fileMetadataDesc: "विस्तृत केवल-पढ़ने योग्य फ़ाइल मेटाडेटा और पैरामीटर",
    properties: "गुण",
    uploadDate: "अपलोड की तारीख",
    projectReference: "परियोजना संदर्भ",
    downloadFileRaw: "रॉ फ़ाइल डाउनलोड करें",
    noDescriptionProvided: "इस फ़ाइल के लिए कोई विवरण नहीं दिया गया है।",
    storageKey: "स्टोरेज कुंजी",
    backToFiles: "फ़ाइलों पर वापस जाएं",
    recurringInvoices: "आवर्ती चालान",
    invoicesCount: "चालान",
    recurringActiveCount: "आवर्ती सदस्यताएं सक्रिय",
    awaitingPayment: "भुगतान की प्रतीक्षा है",
    transactionHistory: "लेनदेन का इतिहास",
    noTransactionsYet: "अभी तक कोई लेनदेन नहीं हुआ है।",
    transaction: "लेनदेन",
    method: "विधि",
    completePayment: "भुगतान पूरा करें",
    paying: "भुगतान किया जा रहा है",
    pleaseWaitDoNotClose: "कृपया प्रतीक्षा करें, इस विंडो को बंद न करें।",
    paymentReceiptGenerated: "एक मॉक रसीद जनरेट की गई है।",
    done: "हो गया",
    createSubscriptionTemplate: "सदस्यता टेम्पलेट बनाएं",
    billingFrequency: "बिलिंग आवृत्ति",
    firstBillingDate: "प्रथम बिलिंग तिथि",
    gstTaxRate: "जीएसटी कर दर (%)",
    discountType: "छूट का प्रकार",
    discountValue: "छूट का मूल्य",
    lineItems: "लाइन आइटम",
    addItem: "+ आइटम जोड़ें",
    notesPrintedInvoice: "टिप्पणियाँ (जनरेट किए गए चालान पर प्रिंट होंगी)",
    notesPlaceholderSubscription: "उदा. सदस्यता की शर्तें, बिलिंग जानकारी...",
    pricingCalculationsPreview: "मूल्य गणना का पूर्वावलोकन",
    totalAmount: "कुल राशि",
    saveTemplate: "टेम्पलेट सहेजें",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    quarterly: "त्रैमासिक",
    percentage: "प्रतिशत (%)",
    flatAmount: "निश्चित राशि",
    accountHolder: "खाता धारक",
    bankName: "बैंक का नाम",
    accountNumber: "खाता संख्या",
    ifscCode: "आईएफएससी कोड",
    upiId: "यूपीआई आईडी",
    scanToPayUPI: "यूपीआई के माध्यम से भुगतान करने के लिए स्कैन करें",
    scanUsingUpiApps: "BHIM, GPay, PhonePe, या Paytm का उपयोग करके स्कैन करें",
    pay: "भुगतान करें",
    close: "बंद करें",
    stripeCardCheckout: "स्ट्राइप कार्ड चेकアウト",
    stripeDesc: "वीज़ा, मास्टरकार्ड, एमेक्स, एप्पल पे",
    paypalCheckout: "पेपैल चेकआउट",
    paypalDesc: "पेपैल बैलेंस या खाते के माध्यम से भुगतान करें",
    wiseTransfer: "वाइज डायरेक्ट ट्रांसफर",
    wiseDesc: "सीधे अंतरराष्ट्रीय बैंक ट्रांसफर का अनुकरण करें",
    upiDesc: "गूगल पे, फोनपे, पेटीएम",
    cardDesc: "वीज़ा, मास्टरकार्ड, रुपे",
    netbankingDesc: "सभी प्रमुख बैंक",
    creditDebitCard: "क्रेडिट / डेबिट कार्ड",
    netBanking: "नेट बैंकिंग",
    payNow: "अभी भुगतान करें",
    sendInvoice: "चालान भेजें",
    taxRate: "कर की दर",
    zeroRatedGst: "शून्य-रेटेड जीएसटी",
    cgst: "सीजीएसटी",
    sgst: "एसजीएसटी",
    igst: "आईजीएसटी",
    rcmWarning: "रिवर्स चार्ज (RCM) के तहत देय जीएसटी। कर को चालान कुल में नहीं जोड़ा गया है।",
    roundingOff: "राउंडिंग ऑफ",
    totalExclGst: "कुल (जीएसटी को छोड़कर)",
    totalInvoiceValue: "कुल चालान मूल्य",
    tdsWithheld: "टीडीएस रोका गया",
    netPayableDue: "शुद्ध देय / बकाया",
    bankTransferDetails: "बैंक ट्रांसफर का विवरण",
    placeOfSupply: "आपूर्ति का स्थान",
    dateFilter: "तारीख",
    today: "आज",
    thisWeek: "इस सप्ताह",
    thisMonth: "इस महीने",
    thisYear: "इस वर्ष",
    customRange: "कस्टम रेंज",
    from: "से",
    to: "तक",
    overdue: "अतिदेय",
    sent: "भेजा गया",
    paid: "भुगतान किया गया",
    agencyProfile: "एजेंसी प्रोफ़ाइल",
    emailSettings: "ईमेल सेटिंग्स",
    notificationPreferences: "अधिसूचना प्राथमिकताएँ",
    securitySettings: "सुरक्षा सेटिंग्स",
    brandingConfiguration: "ब्रांडिंग कॉन्फ़िगरेशन",
    settingsDescZenithOS: "अपने ZenithOS कॉन्फ़िगरेशन को प्रबंधित करें",
    companyLogo: "कंपनी का लोगो",
    agencyName: "एजेंसी का नाम",
    website: "वेबसाइट",
    contactEmail: "संपर्क ईमेल",
    gstNumber: "जीएसटी नंबर",
    saveChanges: "परिवर्तन सहेजें",
    emailProvider: "ईमेल प्रदाता",
    poweredBy: "द्वारा संचालित",
    senderName: "प्रेषक का नाम",
    senderEmail: "प्रेषक का ईमेल",
    automatedEmails: "स्वचालित ईमेल",
    welcomeEmailClient: "ग्राहक निर्माण पर स्वागत ईमेल",
    approvalRequestNotif: "स्वीकृति अनुरोध सूचनाएं",
    invoiceDeliveryEmails: "चालान वितरण ईमेल",
    paymentReceiptEmails: "भुगतान रसीद ईमेल",
    deadlineReminders: "समय सीमा अनुस्मारक",
    saveSettings: "सेटिंग्स सहेजें",
    newClientAdded: "नया ग्राहक जोड़ा गया",
    newClientAddedDesc: "जब एक नया ग्राहक बनाया जाता है",
    projectAssignedYou: "परियोजना आपको सौंपी गई",
    projectAssignedYouDesc: "जब आपको किसी परियोजना में जोड़ा जाता है",
    approvalReceived: "स्वीकृति प्राप्त हुई",
    approvalReceivedDesc: "जब कोई ग्राहक स्वीकृति अनुरोध का जवाब देता है",
    paymentReceived: "भुगतान प्राप्त हुआ",
    paymentReceivedDesc: "जब एक चालान का भुगतान किया जाता है",
    deadlineApproaching: "समय सीमा निकट आ रही है",
    deadlineApproachingDesc: "परियोजना की समय सीमा से 3 दिन पहले",
    invoiceOverdue: "चालान अतिदेय",
    invoiceOverdueDesc: "जब एक चालान अपनी देय तिथि पार कर जाता है",
    savePreferences: "प्राथमिकताएं सहेजें",
    currentPassword: "वर्तमान पासवर्ड",
    newPassword: "नया पासवर्ड",
    confirmNewPassword: "नए पासवर्ड की पुष्टि करें",
    sessionManagement: "सत्र प्रबंधन",
    sessionManagementDesc: "JWT टोकन 7 दिनों के बाद समाप्त हो जाते हैं। रिफ्रेश टोकन 30 दिनों के लिए वैध होते हैं।",
    loggedOutInactivity: "निष्क्रियता के कारण आपको लॉग आउट कर दिया गया है।",
    updatePassword: "पासवर्ड अपडेट करें",
    agencyBrandName: "एजेंसी/ब्रांड का नाम",
    brandAccentTheme: "ब्रांड एक्सेंट थीम",
    brandLogoUrl: "ब्रांड लोगो URL",
    invoiceFooterText: "चालान फ़ुटर टेक्स्ट",
    saveBranding: "ब्रांडिंग सहेजें",
    orangeDefault: "नारंगी (डिफ़ॉल्ट)",
    blueAccent: "नीला",
    emeraldAccent: "पन्ना",
    indigoAccent: "इंडिगो",
    violetAccent: "बैंगनी",
    welcomeBack: "आपका स्वागत है",
    approvalsWaiting: "स्वीकृतियाँ लंबित",
    invoicesOutstanding: "चालान बकाया",
    completedTasksOf: "कार्य पूर्ण",
    pending: "लंबित",
    signatureStylePreview: "शैली का पूर्वावलोकन",
    liveSignaturePreview: "लाइव हस्ताक्षर पूर्वावलोकन",
    initialsPlaceholder: "प्रारंभिक अक्षर (अधिकतम 3 अक्षर)",
    liveStampPreview: "लाइव स्टैम्प पूर्वावलोकन",
    commentNoteOptional: "टिप्पणी/नोट (वैकल्पिक)",
    addCommentNotePlaceholder: "एक टिप्पणी या नोट जोड़ें...",
    goBack: "वापस जाएं",
    signApprove: "हस्ताक्षर करें और स्वीकृत करें",
    specifyRevisionsRequired: "सटीक रूप से निर्दिष्ट करें कि क्या परिवर्तन आवश्यक हैं...",
    noInvoices: "कोई चालान नहीं",
    noInvoicesFoundAccount: "आपके खाते के लिए कोई चालान नहीं मिला।",
    createFirstInvoice: "ग्राहकों को भेजने के लिए अपना पहला चालान बनाएं।",
    client: "ग्राहक",
    inclTax: "कर सहित",
    nextBillingDate: "अगली बिलिंग तिथि",
    invoiceDetails: "चालान का विवरण",
    taxableValue: "कर योग्य मूल्य",
    orderId: "ऑर्डर आईडी",
    paymentReceivedSuccess: "सफलतापूर्वक प्राप्त हुआ।",
    transactionsRecorded: "लेनदेन दर्ज किए गए",
    totalCollected: "कुल संकलित",
    pendingInvoices: "लंबित चालान",
    failed: "विफल",
    partial: "आंशिक",
    received: "प्राप्त हुआ",
    inApp: "इन-ऐप",
    security: "सुरक्षा",
    clientPortalWelcomeMessage: "क्लाइंट पोर्टल स्वागत संदेश",
    brandingSaved: "ब्रांडिंग कॉन्फ़िगरेशन सफलतापूर्वक सहेजे गए और लागू किए गए!",
    youHave: "आपके पास",
    and: "और",
    of: "में से",
    approve: "स्वीकृत करें",
    noCompletedApprovalsYet: "अभी तक कोई पूर्ण स्वीकृति नहीं है।",
    noSharedFiles: "अभी तक आपके साथ कोई फ़ाइल साझा नहीं की गई है।",
    action: "कार्रवाई",
    receipt: "रसीद",
    pdfSimulated: "इस वातावरण के लिए पीडीएफ जेनरेशन सिम्युलेटेड है।",
    assetForReview: "समीक्षा के लिए संपत्ति",
    selectResponseChoice: "कृपया नीचे अपनी प्रतिक्रिया का चयन करें:",
    simulatePayment: "भुगतान का अनुकरण करें",
    hsnSac: "एचएसएन/एसएसी",
    qty: "मात्रा",
    flat: "फ्लैट",
    lutNo: "एलयूटी संख्या",
    invoice: "चालान",
    agreeToTermsError: "आपको कानूनी रूप से बाध्यकारी शर्तों से सहमत होना होगा।",
    typeSignatureError: "कृपया हस्ताक्षर के लिए अपना नाम टाइप करें।",
    stampInitialsError: "कृपया स्टैम्प सील के लिए अपने आद्याक्षर दर्ज करें।"
  },
  es: {
    dashboard: "Tablero",
    clients: "Clientes",
    projects: "Proyectos",
    tasks: "Tareas",
    files: "Archivos",
    approvals: "Aprobaciones",
    invoices: "Facturas",
    payments: "Pagos",
    proposals: "Propuestas",
    contracts: "Contratos",
    settings: "Ajustes",
    logout: "Cerrar sesión",
    welcome: "Bienvenido",
    createInvoice: "Crear factura",
    newInvoice: "Nueva factura",
    taxTemplate: "Plantilla de impuestos",
    currency: "Moneda",
    billingModel: "Modelo de facturación",
    fixed: "Precio fijo",
    hourly: "Facturación por horas",
    gstr1Export: "Exportar GSTR-1",
    language: "Idioma",
    whiteLabel: "Branding personalizado",
    theme: "Tema",
    notifications: "Notificaciones",
    totalRevenue: "Ingresos totales",
    activeProjects: "Proyectos activos",
    pendingApprovals: "Aprobaciones pendientes",
    overdueInvoices: "Facturas vencidas",
    recentActivity: "Actividad reciente",
    search: "Buscar",
    add: "Añadir",
    edit: "Editar",
    delete: "Eliminar",
    view: "Ver",
    save: "Guardar",
    cancel: "Cancelar",
    status: "Estado",
    name: "Nombre",
    email: "Correo",
    phone: "Teléfono",
    actions: "Acciones",
    amount: "Monto",
    date: "Fecha",
    dueDate: "Fecha de vencimiento",
    description: "Descripción",
    billing: "Facturación",
    total: "Total",
    tax: "Impuesto",
    subtotal: "Subtotal",
    discount: "Descuento",
    rate: "Tarifa",
    quantity: "Cantidad",
    priority: "Prioridad",
    assignee: "Asignado",
    recent: "Reciente",
    settingsDesc: "Administre las preferencias y configuraciones de su agencia",
    dashboardDesc: "Operaciones de la agencia de un vistazo",
    clientsDesc: "Administre las relaciones y los portales de los clientes",
    projectsDesc: "Realice un seguimiento de los hitos activos y del alcance",
    tasksDesc: "Administre las tareas pendientes del proyecto",
    filesDesc: "Almacenamiento de activos del cliente y aprobaciones",
    active: "Activo",
    review: "Revisión",
    completed: "Completado",
    draft: "Borrador",
    archived: "Archivado",
    goodMorning: "Buenos días",
    dashboardSubtitle: "Esto es lo que está pasando en Zenith Creative hoy.",
    editDashboard: "Editar Tablero",
    welcomeTitle: "¡Bienvenido a ZenithOS!",
    onboardingDesc: "Comience completando estos rápidos pasos para explorar la plataforma.",
    dismiss: "Descartar",
    inactive: "Inactivo",
    backToClients: "Volver a Clientes",
    contactInformation: "Información de Contacto",
    gstFinancialDetails: "Detalles de GST y Financieros",
    noGstRegistered: "Sin GST registrado",
    noPanRegistered: "Sin PAN registrado",
    noProjectsAssigned: "No hay proyectos asignados actualmente a este cliente.",
    noInvoicesRecorded: "No hay facturas registradas para este cliente.",
    invoiceNumber: "Nº de Factura",
    recipientNumber: "Número de destinatario:",
    whatsappPlaceholder: "Escriba el mensaje de alerta de WhatsApp...",
    sending: "Enviando...",
    selected: "seleccionado",
    commaSeparated: "separados por comas",
    step: "Paso",
    addClient: "Añadir Cliente",
    onboardingClientDesc: "Cree su primera entrada de cliente en el CRM.",
    defineProject: "Definir un Proyecto",
    onboardingProjectDesc: "Asigne trabajo, equipo y presupuesto.",
    issueInvoice: "Emitir una Factura",
    onboardingInvoiceDesc: "Facture al cliente y establezca fechas de vencimiento.",
    checkClientPortal: "Comprobar Portal del Cliente",
    onboardingPortalDesc: "Inicie sesión como client@novatech.com.",
    dashboardEditMode: "Modo de Edición del Tablero",
    dashboardEditDesc: "Reorganice secciones, alterne la visibilidad y ajuste los anchos. Guarde sus personalizaciones a continuación.",
    resetDefaults: "Restablecer valores predeterminados",
    saveLayout: "Guardar Diseño",
    totalClients: "Total de Clientes",
    monthlyRevenue: "Ingresos Mensuales",
    outstanding: "Pendiente",
    revenueOverview: "Resumen de Ingresos",
    billedVsCollected: "Facturado vs. Recaudado",
    billed: "Facturado",
    collected: "Recaudado",
    threeMonths: "3 Meses",
    sixMonths: "6 Meses",
    twelveMonths: "12 Meses",
    projectStatus: "Estado del Proyecto",
    currentBreakdown: "Desglose actual",
    viewAll: "Ver todo",
    due: "Vencimiento",
    all: "Todos",
    overdueInvoicesAlert: "Alerta de Facturas Vencidas",
    overdueInvoicesTitle: "Facturas Vencidas",
    overdueInvoicesDesc: "factura(s) han pasado su fecha de vencimiento.",
    noOverdueInvoices: "No hay facturas vencidas actualmente.",
    sendReminder: "Enviar Recordatorio",
    reminderEmailSent: "¡Correo de recordatorio enviado con éxito!",
    totalClientsDesc: "total",
    activeClientsDesc: "activo",
    searchPlaceholderClients: "Buscar por nombre, contacto, GST, etiquetas...",
    filters: "Filtros",
    listGrid: "Cuadrícula de Lista",
    kanbanPipeline: "Pipeline Kanban",
    allStatuses: "Todos los Estados",
    lead: "Prospecto",
    industry: "Industria",
    allIndustries: "Todas las Industrias",
    technology: "Tecnología",
    hospitality: "Hostelería",
    fmcg: "Bienes de consumo",
    realEstate: "Bienes Raíces",
    education: "Educación",
    media: "Medios",
    other: "Otro",
    revenueRange: "Rango de Ingresos",
    allRanges: "Todos los Rangos",
    highRange: "Alto (≥ ₹3L)",
    mediumRange: "Medio (₹1L - ₹3L)",
    lowRange: "Bajo (< ₹1L)",
    sortBy: "Ordenar Por",
    companyNameAsc: "Nombre de Empresa (A-Z)",
    companyNameDesc: "Nombre de Empresa (Z-A)",
    revenueDesc: "Ingresos (Alto a Bajo)",
    projectsCountDesc: "Cantidad de Proyectos (Alto a Bajo)",
    noClientsFound: "No se encontraron clientes",
    noClientsFoundDesc: "Intente ajustar sus filtros o agregue un nuevo registro de cliente.",
    exportCsv: "Exportar CSV",
    deleteMultipleClients: "¿Eliminar Varios Clientes?",
    deleteMultipleClientsDesc: "¿Está seguro de que desea eliminar permanentemente estos clientes seleccionados? Esta acción es destructiva y no se puede deshacer.",
    deleteClientTitle: "¿Eliminar Cliente?",
    deleteClientDesc: "¿Está seguro de que desea eliminar permanentemente este cliente? Esta acción es destructiva y no se puede deshacer.",
    companyName: "Nombre de la Empresa",
    contactPerson: "Persona de Contacto",
    address: "Dirección",
    notes: "Notas",
    gstin: "GSTIN",
    pan: "PAN",
    tags: "Etiquetas",
    customMetadata: "Campos de Metadatos Personalizados",
    remove: "Eliminar",
    addCustomField: "+ Agregar Campo Personalizado",
    createClient: "Crear Cliente",
    clientCreatedSuccessfully: "Cliente creado con éxito.",
    clientDeletedSuccessfully: "Cliente eliminado con éxito.",
    selectedClientsDeleted: "Clientes seleccionados eliminados con éxito.",
    gstinCopied: "¡GSTIN copiado al portapapeles!",
    panCopied: "¡PAN copiado al portapapeles!",
    whatsappAlert: "Simular Alerta de WhatsApp",
    whatsappUnavailable: "WhatsApp no disponible",
    noPhoneRegistered: "No hay número de teléfono registrado para el cliente.",
    sendWhatsapp: "Enviar Mensaje de WhatsApp",
    whatsappSent: "Mensaje de WhatsApp simulado enviado",
    interactionType: "Registrar Llamada, Correo o Nota",
    typeInteractionSummary: "Escriba el resumen de la comunicación...",
    saveInteraction: "Registrar Interacción",
    saving: "Guardando...",
    interactionLogged: "Interacción de actividad registrada con éxito",
    timelineTitle: "Línea de Tiempo del Historial de Comunicaciones",
    noHistory: "No hay historial de comunicaciones registrado aún.",
    loggedBy: "Registrado por",
    systemAuditLogs: "Logs de Auditoría del Sistema",
    noActivity: "No se ha registrado actividad para este cliente.",
    establishedClient: "Cliente establecido desde",
    newProject: "Nuevo Proyecto",
    searchProjects: "Buscar proyectos...",
    budget: "Presupuesto",
    daysOverdue: "d de retraso",
    daysLeft: "d restantes",
    deleteProjectTitle: "¿Eliminar Proyecto?",
    deleteProjectDesc: "¿Está seguro de que desea eliminar permanentemente este proyecto? Esta acción es destructiva y no se puede deshacer.",
    deleteMultipleProjects: "¿Eliminar Varios Proyectos?",
    deleteMultipleProjectsDesc: "¿Está seguro de que desea eliminar permanentemente estos proyectos seleccionados? Esta acción es destructiva y no se puede deshacer.",
    createProject: "Crear Proyecto",
    projectName: "Nombre del Proyecto",
    selectClient: "Seleccionar cliente...",
    assignedUser: "Usuario Asignado",
    selectResponsibleUser: "Seleccionar usuario responsable...",
    startDate: "Fecha de Inicio",
    deadline: "Fecha Límite",
    defaultTaxRate: "Tasa de Impuestos por Defecto (%)",
    defaultDiscountRate: "Tasa de Descuento por Defecto (%)",
    projectCreatedSuccessfully: "Proyecto creado con éxito.",
    projectDeletedSuccessfully: "Proyecto eliminado con éxito.",
    selectedProjectsDeleted: "Proyectos seleccionados eliminados con éxito.",
    addTask: "Añadir Tarea",
    viewKanban: "Kanban",
    viewList: "Lista",
    taskPending: "Pendiente",
    taskInProgress: "En Progreso",
    taskReview: "En Revisión",
    taskDone: "Terminada",
    noTasksInStatus: "No hay tareas actualmente en este estado.",
    createTask: "Crear Tarea",
    taskTitle: "Título de la Tarea",
    selectProject: "Seleccionar proyecto...",
    selectAssignee: "Seleccionar asignado...",
    taskCreatedSuccessfully: "Tarea creada con éxito.",
    taskStatusUpdated: "Estado de la tarea actualizado.",
    selectedTasksDeleted: "Tareas seleccionadas eliminadas con éxito.",
    tasksMarkedDone: "Tareas marcadas como completadas.",
    ticking: "Contando",
    startTracking: "Iniciar temporizador",
    stopTimer: "Detener temporizador",
    manualTimeLog: "Registrar hoja de tiempo manual",
    minutes: "Minutos",
    whatWork: "¿En qué trabajó?",
    logTimeSheet: "Registrar Sesión de Tiempo",
    timeHistory: "Historial de registro de tiempo",
    noTimeHistory: "No hay registros de tiempo guardados para esta tarea aún.",
    sessionSummary: "Resumen de la Sesión",
    stopAndLog: "Detener y Registrar",
    uploadFiles: "Subir Archivos",
    dragDropFiles: "Arrastre y suelte archivos aquí",
    orBrowse: "o navegue para subir",
    fileTypesSupported: "Todos los tipos de archivo soportados (Máx. 100MB)",
    searchFiles: "Buscar archivos...",
    fileDetails: "Detalles del Archivo",
    fileType: "Tipo",
    fileSize: "Tamaño",
    uploadedBy: "Subido Por",
    openMetadata: "Abrir Página de Metadatos",
    editFile: "Editar Archivo",
    project: "Proyecto",
    fileSelect: "Archivo",
    renameFile: "Renombrar Archivo (Opcional)",
    descriptionOptional: "Descripción (Opcional)",
    fileConflict: "Ya existe un archivo con este nombre.",
    uploadAsNewVersion: "Subir como nueva versión (incrementar versión)",
    overwriteExisting: "Sobrescribir/reemplazar entrada de archivo existente",
    upload: "Subir",
    fileUploadedSuccessfully: "Archivo subido con éxito.",
    fileDeletedSuccessfully: "Archivo eliminado con éxito.",
    deleteFileTitle: "¿Eliminar Archivo?",
    deleteFileDesc: "Are you sure you want to permanently delete this file? This action is destructive and cannot be undone.",
    exportGstr1: "Exportar GSTR-1",
    allInvoices: "Todas las Facturas",
    recurringSubscriptions: "Suscripciones Recurrentes",
    totalBilled: "Total Facturado",
    choosePaymentMethod: "Elegir método de pago",
    securingRazorpay: "Asegurado por Razorpay (Modo Mock)",
    downloadPdf: "Descargar PDF",
    gstr1Downloaded: "Reporte GSTR-1 descargado con éxito.",
    invoiceSent: "Factura enviada con éxito.",
    paymentSuccessful: "¡Pago Exitoso!",
    paymentProcessing: "Procesando pago...",
    paymentProcessingDesc: "Comunicándose con los servidores de pago.",
    runTemplate: "Ejecutar Plantilla",
    subscriptionTemplateCreated: "Plantilla de suscripción recurrente creada con éxito.",
    subscriptionTemplateDeleted: "Plantilla recurrente eliminada.",
    invoiceGeneratedFromTemplate: "¡Factura generada con éxito a partir de esta plantilla!",
    myPortal: "Mi Portal",
    sharedFiles: "Archivos Compartidos",
    myInvoices: "Mis Facturas",
    myProjects: "Mis Proyectos",
    history: "Historial",
    allCaughtUp: "¡Todo al día! Sin aprobaciones pendientes.",
    requestChanges: "Solicitar Cambios",
    feedbackLabel: "Comentarios del Cliente",
    digitallySigned: "Firmado Digitalmente y Verificado",
    timestamp: "Marca de tiempo",
    respondToApproval: "Responder a la Aprobación",
    approveAndSign: "Aprobar y Firmar",
    eSignatureVerification: "Verificación de Firma Electrónica",
    typeSignature: "Escribir Firma",
    sealStamp: "Sello de Firma",
    typeName: "Escriba su Nombre Completo",
    signatureStyle: "Estilo de Firma",
    consentText: "Acepto que esta firma es una representación válida y legalmente vinculante de mi aprobación, firma electrónica y consentimiento.",
    whyRevisionsNeeded: "¿Por qué son necesarias las revisiones?",
    submitRevisionRequest: "Enviar Solicitud de Revisión",
    assetApprovedAndSigned: "Activo aprobado y firmado con éxito.",
    revisionRequested: "Revisión solicitada.",
    filesAcrossProjects: "archivos en todos los proyectos",
    pleaseSelectFileAndProject: "Por favor, seleccione un archivo y un proyecto para subir.",
    fileRenamedSuccessfully: "Archivo renombrado con éxito.",
    file: "Archivo",
    version: "Versión",
    downloads: "Descargas",
    download: "Descargar",
    noFilesFound: "No se encontraron archivos",
    noFilesFoundDesc: "Suba su primer archivo o ajuste su búsqueda.",
    leaveEmptyOriginalName: "Dejar vacío para usar el nombre original",
    addBriefDescription: "Añada una breve descripción del archivo...",
    fileMetadata: "Metadatos del archivo",
    fileNotFound: "Archivo no encontrado",
    fileNotFoundDesc: "El archivo solicitado no se pudo encontrar o ha sido eliminado.",
    fileMetadataDesc: "Parámetros y metadatos de archivo detallados de solo lectura",
    properties: "Propiedades",
    uploadDate: "Fecha de carga",
    projectReference: "Referencia del proyecto",
    downloadFileRaw: "Descargar archivo sin procesar",
    noDescriptionProvided: "No se proporcionó ninguna descripción para este archivo.",
    storageKey: "Clave de almacenamiento",
    backToFiles: "Volver a Archivos",
    recurringInvoices: "Facturas recurrentes",
    invoicesCount: "facturas",
    recurringActiveCount: "suscripciones recurrentes activas",
    awaitingPayment: "A la espera del pago",
    transactionHistory: "Historial de transacciones",
    noTransactionsYet: "Aún no hay transacciones.",
    transaction: "Transacción",
    method: "Método",
    completePayment: "Completar pago",
    paying: "Pagando",
    pleaseWaitDoNotClose: "Por favor espere, no cierre esta ventana.",
    paymentReceiptGenerated: "Se ha generado un recibo simulado.",
    done: "Hecho",
    createSubscriptionTemplate: "Crear plantilla de suscripción",
    billingFrequency: "Frecuencia de facturación",
    firstBillingDate: "Primera fecha de facturación",
    gstTaxRate: "Tasa de impuesto GST (%)",
    discountType: "Tipo de descuento",
    discountValue: "Valor de descuento",
    lineItems: "Líneas de detalle",
    addItem: "+ Añadir artículo",
    notesPrintedInvoice: "Notas (impresas en la factura generada)",
    notesPlaceholderSubscription: "Ej. Términos de suscripción, información de facturación...",
    pricingCalculationsPreview: "Vista previa de cálculos de precios",
    totalAmount: "Monto total",
    saveTemplate: "Guardar plantilla",
    weekly: "Semanal",
    monthly: "Mensual",
    quarterly: "Trimestral",
    percentage: "Porcentaje (%)",
    flatAmount: "Monto fijo",
    accountHolder: "Titular de la cuenta",
    bankName: "Nombre del banco",
    accountNumber: "Número de cuenta",
    ifscCode: "Código IFSC",
    upiId: "ID de UPI",
    scanToPayUPI: "Escanear para pagar vía UPI",
    scanUsingUpiApps: "Escanee usando BHIM, GPay, PhonePe o Paytm",
    pay: "Pagar",
    close: "Cerrar",
    stripeCardCheckout: "Pago con tarjeta Stripe",
    stripeDesc: "Visa, Mastercard, AMEX, Apple Pay",
    paypalCheckout: "Pago con PayPal",
    paypalDesc: "Pague con saldo o cuenta de PayPal",
    wiseTransfer: "Transferencia directa Wise",
    wiseDesc: "Simular transferencia bancaria internacional directa",
    upiDesc: "Google Pay, PhonePe, Paytm",
    cardDesc: "Visa, Mastercard, RuPay",
    netbankingDesc: "Todos los bancos principales",
    creditDebitCard: "Tarjeta de crédito / débito",
    netBanking: "Banca por internet",
    payNow: "Pagar ahora",
    sendInvoice: "Enviar factura",
    taxRate: "Tasa de impuesto",
    zeroRatedGst: "GST tasa cero",
    cgst: "CGST",
    sgst: "SGST",
    igst: "IGST",
    rcmWarning: "GST pagadero bajo Cargo Reverso (RCM). El impuesto NO se añade al total de la factura.",
    roundingOff: "Redondeo",
    totalExclGst: "Total (sin GST)",
    totalInvoiceValue: "Valor total de la factura",
    tdsWithheld: "TDS retenido",
    netPayableDue: "Neto a pagar / adeudado",
    bankTransferDetails: "Detalles de transferencia bancaria",
    placeOfSupply: "Lugar de suministro",
    dateFilter: "Fecha",
    today: "Hoy",
    thisWeek: "Esta semana",
    thisMonth: "Este mes",
    thisYear: "Este año",
    customRange: "Rango personalizado",
    from: "de",
    to: "a",
    overdue: "Vencida",
    sent: "Enviada",
    paid: "Pagada",
    agencyProfile: "Perfil de la agencia",
    emailSettings: "Ajustes de correo",
    notificationPreferences: "Preferencias de notificaciones",
    securitySettings: "Ajustes de seguridad",
    brandingConfiguration: "Configuración de branding",
    settingsDescZenithOS: "Administre su configuración de ZenithOS",
    companyLogo: "Logo de la empresa",
    agencyName: "Nombre de la agencia",
    website: "Sitio web",
    contactEmail: "Correo de contacto",
    gstNumber: "Número de GST",
    saveChanges: "Guardar cambios",
    emailProvider: "Proveedor de correo",
    poweredBy: "Desarrollado por",
    senderName: "Nombre del remitente",
    senderEmail: "Correo del remitente",
    automatedEmails: "Correos automatizados",
    welcomeEmailClient: "Correo de bienvenida al crear cliente",
    approvalRequestNotif: "Notificaciones de solicitud de aprobación",
    invoiceDeliveryEmails: "Correos de entrega de facturas",
    paymentReceiptEmails: "Correos de recibo de pago",
    deadlineReminders: "Recordatorios de fechas límite",
    saveSettings: "Guardar ajustes",
    newClientAdded: "Nuevo cliente añadido",
    newClientAddedDesc: "Cuando se crea un nuevo cliente",
    projectAssignedYou: "Proyecto asignado a usted",
    projectAssignedYouDesc: "Cuando se le añade a un proyecto",
    approvalReceived: "Aprobación recibida",
    approvalReceivedDesc: "Cuando un cliente responde a una solicitud de aprobación",
    paymentReceived: "Pago recibido",
    paymentReceivedDesc: "Cuando se paga una factura",
    deadlineApproaching: "Fecha límite cercana",
    deadlineApproachingDesc: "3 días antes de la fecha límite del proyecto",
    invoiceOverdue: "Factura vencida",
    invoiceOverdueDesc: "Cuando una factura supera su fecha de vencimiento",
    savePreferences: "Guardar preferencias",
    currentPassword: "Contraseña actual",
    newPassword: "Nueva contraseña",
    confirmNewPassword: "Confirmar nueva contraseña",
    sessionManagement: "Gestión de sesiones",
    sessionManagementDesc: "Los tokens JWT expiran después de 7 días. Los tokens de actualización son válidos por 30 días.",
    loggedOutInactivity: "Se ha cerrado su sesión debido a la inactividad.",
    updatePassword: "Actualizar contraseña",
    agencyBrandName: "Nombre de la agencia/marca",
    brandAccentTheme: "Tema de acento de marca",
    brandLogoUrl: "URL del logo de marca",
    invoiceFooterText: "Texto de pie de factura",
    saveBranding: "Guardar branding",
    orangeDefault: "Naranja (Por defecto)",
    blueAccent: "Azul",
    emeraldAccent: "Esmeralda",
    indigoAccent: "Índigo",
    violetAccent: "Violeta",
    welcomeBack: "Bienvenido de nuevo",
    approvalsWaiting: "aprobaciones en espera",
    invoicesOutstanding: "facturas pendientes",
    completedTasksOf: "tareas completadas",
    pending: "Pendiente",
    signatureStylePreview: "Vista previa de estilo",
    liveSignaturePreview: "Vista previa de firma en vivo",
    initialsPlaceholder: "Iniciales (máx 3 letras)",
    liveStampPreview: "Vista previa de sello en vivo",
    commentNoteOptional: "Comentario/Nota (opcional)",
    addCommentNotePlaceholder: "Añada un comentario o nota...",
    goBack: "Volver",
    signApprove: "Firmar y aprobar",
    specifyRevisionsRequired: "Especifique exactamente qué cambios se requieren...",
    noInvoices: "No hay facturas",
    noInvoicesFoundAccount: "No se encontraron facturas para su cuenta.",
    createFirstInvoice: "Cree su primera factura para enviar a los clientes.",
    client: "Cliente",
    inclTax: "impuesto incl.",
    nextBillingDate: "Próxima fecha de facturación",
    invoiceDetails: "Detalles de la factura",
    taxableValue: "Valor gravable",
    orderId: "ID de pedido",
    paymentReceivedSuccess: "recibido con éxito.",
    transactionsRecorded: "transacciones registradas",
    totalCollected: "Total Recaudado",
    pendingInvoices: "Facturas Pendientes",
    failed: "Fallido",
    partial: "Parcial",
    received: "recibido",
    inApp: "En la aplicación",
    security: "Seguridad",
    clientPortalWelcomeMessage: "Mensaje de bienvenida del portal del cliente",
    brandingSaved: "¡Configuraciones de marca guardadas y aplicadas con éxito!",
    youHave: "Tiene",
    and: "y",
    of: "de",
    approve: "Aprobar",
    noCompletedApprovalsYet: "Aún no hay aprobaciones completadas.",
    noSharedFiles: "Aún no se han compartido archivos con usted.",
    action: "Acción",
    receipt: "Recibo",
    pdfSimulated: "La generación de PDF está simulada para este entorno.",
    assetForReview: "Activo para revisión",
    selectResponseChoice: "Por favor, seleccione su opción de respuesta a continuación:",
    simulatePayment: "Simular pago",
    hsnSac: "HSN/SAC",
    qty: "Cant",
    flat: "Fijo",
    lutNo: "Nº de LUT",
    invoice: "Factura",
    agreeToTermsError: "Debe estar de acuerdo con los términos legalmente vinculantes.",
    typeSignatureError: "Por favor, escriba su nombre para la firma.",
    stampInitialsError: "Por favor, introduzca sus iniciales para el sello."
  },
  fr: {
    dashboard: "Tableau de bord",
    clients: "Clients",
    projects: "Projets",
    tasks: "Tâches",
    files: "Fichiers",
    approvals: "Approbations",
    invoices: "Factures",
    payments: "Paiements",
    proposals: "Propositions",
    contracts: "Contrats",
    settings: "Paramètres",
    logout: "Se déconnecter",
    welcome: "Bienvenue",
    createInvoice: "Créer une facture",
    newInvoice: "Nouvelle facture",
    taxTemplate: "Modèle de taxe",
    currency: "Devise",
    billingModel: "Modèle de facturation",
    fixed: "Prix fixe",
    hourly: "Facturation horaire",
    gstr1Export: "Exporter GSTR-1",
    language: "Langue",
    whiteLabel: "Marque personnalisée",
    theme: "Thème",
    notifications: "Notifications",
    totalRevenue: "Revenu total",
    activeProjects: "Projets actifs",
    pendingApprovals: "Approbations en attente",
    overdueInvoices: "Factures impayées",
    recentActivity: "Activité récente",
    search: "Rechercher",
    add: "Ajouter",
    edit: "Modifier",
    delete: "Supprimer",
    view: "Voir",
    save: "Enregistrer",
    cancel: "Annuler",
    status: "Statut",
    name: "Nom",
    email: "Email",
    phone: "Téléphone",
    actions: "Actions",
    amount: "Montant",
    date: "Date",
    dueDate: "Date d'échéance",
    description: "Description",
    billing: "Facturation",
    total: "Total",
    tax: "Taxe",
    subtotal: "Sous-total",
    discount: "Remise",
    rate: "Taux",
    quantity: "Quantité",
    priority: "Priorité",
    assignee: "Assigné à",
    recent: "Récent",
    settingsDesc: "Gérez les préférences et les paramètres de votre agence",
    dashboardDesc: "Opérations de l'agence en un coup d'œil",
    clientsDesc: "Gérez les relations clients et les portails",
    projectsDesc: "Suivez les jalons actifs et la portée",
    tasksDesc: "Gérez les tâches à faire du projet",
    filesDesc: "Stockage des actifs des clients et approbations",
    active: "Actif",
    review: "Examen",
    completed: "Complété",
    draft: "Brouillon",
    archived: "Archivé",
    goodMorning: "Bonjour",
    dashboardSubtitle: "Voici ce qui se passe chez Zenith Creative aujourd'hui.",
    editDashboard: "Modifier le Tableau de bord",
    welcomeTitle: "Bienvenue sur ZenithOS !",
    onboardingDesc: "Commencez par suivre ces étapes rapides pour explorer la plateforme.",
    dismiss: "Ignorer",
    inactive: "Inactif",
    backToClients: "Retour aux Clients",
    contactInformation: "Informations de Contact",
    gstFinancialDetails: "Détails TPS et Financiers",
    noGstRegistered: "Aucun TPS enregistré",
    noPanRegistered: "Aucun PAN enregistré",
    noProjectsAssigned: "Aucun projet actuellement attribué à ce client.",
    noInvoicesRecorded: "Aucune facture enregistrée pour ce client.",
    invoiceNumber: "N° de Facture",
    recipientNumber: "Numéro du destinataire :",
    whatsappPlaceholder: "Saisissez le message d'alerte WhatsApp...",
    sending: "Envoi en cours...",
    selected: "sélectionné",
    commaSeparated: "séparés par des virgules",
    step: "Étape",
    addClient: "Ajouter un Client",
    onboardingClientDesc: "Créez votre première fiche client dans le CRM.",
    defineProject: "Définir un Projet",
    onboardingProjectDesc: "Attribuez le travail, l'équipe et le budget.",
    issueInvoice: "Émettre une Facture",
    onboardingInvoiceDesc: "Facturez le client et définissez les dates d'échéance.",
    checkClientPortal: "Vérifier le Portail Client",
    onboardingPortalDesc: "Connectez-vous en tant que client@novatech.com.",
    dashboardEditMode: "Mode d'Édition du Tableau de bord",
    dashboardEditDesc: "Réorganisez les sections, basculez la visibilité et ajustez les largeurs. Enregistrez vos personnalisations ci-dessous.",
    resetDefaults: "Réinitialiser par défaut",
    saveLayout: "Enregistrer la Mise en page",
    totalClients: "Nombre Total de Clients",
    monthlyRevenue: "Revenu Mensuel",
    outstanding: "Encours",
    revenueOverview: "Aperçu des Revenus",
    billedVsCollected: "Facturé vs. Encaissé",
    billed: "Facturé",
    collected: "Encaissé",
    threeMonths: "3 Mois",
    sixMonths: "6 Mois",
    twelveMonths: "12 Mois",
    projectStatus: "Statut du Projet",
    currentBreakdown: "Répartition actuelle",
    viewAll: "Voir tout",
    due: "Échéance",
    all: "Tous",
    overdueInvoicesAlert: "Alerte Factures Impayées",
    overdueInvoicesTitle: "Factures Impayées",
    overdueInvoicesDesc: "facture(s) ont dépassé leur date d'échéance.",
    noOverdueInvoices: "Aucune facture impayée actuellement.",
    sendReminder: "Envoyer un Rappel",
    reminderEmailSent: "E-mail de rappel envoyé avec succès !",
    totalClientsDesc: "total",
    activeClientsDesc: "actif",
    searchPlaceholderClients: "Rechercher par nom, contact, GST, tags...",
    filters: "Filtres",
    listGrid: "Grille de Liste",
    kanbanPipeline: "Pipeline Kanban",
    allStatuses: "Tous les Statuts",
    lead: "Prospect",
    industry: "Secteur",
    allIndustries: "Tous les Secteurs",
    technology: "Technologie",
    hospitality: "Hôtellerie",
    fmcg: "Biens de consommation",
    realEstate: "Immobilier",
    education: "Éducation",
    media: "Médias",
    other: "Autre",
    revenueRange: "Tranche de Revenus",
    allRanges: "Toutes les Tranches",
    highRange: "Élevé (≥ ₹3L)",
    mediumRange: "Moyen (₹1L - ₹3L)",
    lowRange: "Faible (< ₹1L)",
    sortBy: "Trier Par",
    companyNameAsc: "Nom de l'Entreprise (A-Z)",
    companyNameDesc: "Nom de l'Entreprise (Z-A)",
    revenueDesc: "Revenus (Élevé à Faible)",
    projectsCountDesc: "Nombre de Projets (Élevé à Faible)",
    noClientsFound: "Aucun client trouvé",
    noClientsFoundDesc: "Essayez d'ajuster vos filtres ou ajoutez une nouvelle fiche client.",
    exportCsv: "Exporter en CSV",
    deleteMultipleClients: "Supprimer Plusieurs Clients ?",
    deleteMultipleClientsDesc: "Êtes-vous sûr de vouloir supprimer définitivement les clients sélectionnés ? Cette action est destructive et irréversible.",
    deleteClientTitle: "Supprimer le Client ?",
    deleteClientDesc: "Êtes-vous sûr de vouloir supprimer définitivement ce client ? Cette action est destructive et irréversible.",
    companyName: "Nom de l'Entreprise",
    contactPerson: "Personne de Contact",
    address: "Adresse",
    notes: "Notes",
    gstin: "GSTIN",
    pan: "PAN",
    tags: "Tags",
    customMetadata: "Champs de Métadonnées Personnalisés",
    remove: "Supprimer",
    addCustomField: "+ Ajouter un Champ Personnalisé",
    createClient: "Créer un Client",
    clientCreatedSuccessfully: "Client créé avec succès.",
    clientDeletedSuccessfully: "Client supprimé avec succès.",
    selectedClientsDeleted: "Clients sélectionnés supprimés avec succès.",
    gstinCopied: "GSTIN copié dans le presse-papiers !",
    panCopied: "PAN copié dans le presse-papiers !",
    whatsappAlert: "Simuler une Alerte WhatsApp",
    whatsappUnavailable: "WhatsApp indisponible",
    noPhoneRegistered: "Aucun numéro de téléphone client enregistré.",
    sendWhatsapp: "Envoyer un Message WhatsApp",
    whatsappSent: "Message WhatsApp simulé envoyé",
    interactionType: "Enregistrer Appel, E-mail ou Note",
    typeInteractionSummary: "Saisissez le résumé de la communication...",
    saveInteraction: "Enregistrer l'Interaction",
    saving: "Enregistrement...",
    interactionLogged: "Interaction d'activité enregistrée avec succès",
    timelineTitle: "Chronologie de l'Historique des Communications",
    noHistory: "Aucun historique de communication enregistré pour le moment.",
    loggedBy: "Enregistré par",
    systemAuditLogs: "Logs d'Audit Système",
    noActivity: "Aucune activité enregistrée pour ce client.",
    establishedClient: "Client établi depuis",
    newProject: "Nouveau Projet",
    searchProjects: "Rechercher des projets...",
    budget: "Budget",
    daysOverdue: "j de retard",
    daysLeft: "j restants",
    deleteProjectTitle: "Supprimer le Projet ?",
    deleteProjectDesc: "Êtes-vous sûr de vouloir supprimer définitivement ce projet ? Cette action est destructive et irréversible.",
    deleteMultipleProjects: "Supprimer Plusieurs Projets ?",
    deleteMultipleProjectsDesc: "Êtes-vous sûr de vouloir supprimer définitivement les projets sélectionnés ? Cette action est destructive et irréversible.",
    createProject: "Créer un Projet",
    projectName: "Nom du Projet",
    selectClient: "Sélectionner un client...",
    assignedUser: "Utilisateur Assigné",
    selectResponsibleUser: "Sélectionner l'utilisateur responsable...",
    startDate: "Date de Début",
    deadline: "Date Limite",
    defaultTaxRate: "Taux de Taxe par Défaut (%)",
    defaultDiscountRate: "Taux de Remise par Défaut (%)",
    projectCreatedSuccessfully: "Projet créé avec succès.",
    projectDeletedSuccessfully: "Projet supprimé avec succès.",
    selectedProjectsDeleted: "Projets sélectionnés supprimés avec succès.",
    addTask: "Ajouter une Tâche",
    viewKanban: "Kanban",
    viewList: "Liste",
    taskPending: "En attente",
    taskInProgress: "En Cours",
    taskReview: "En Révision",
    taskDone: "Terminée",
    noTasksInStatus: "Aucune tâche actuellement dans ce statut.",
    createTask: "Créer une Tâche",
    taskTitle: "Titre de la Tâche",
    selectProject: "Sélectionner un projet...",
    selectAssignee: "Sélectionner un assigné...",
    taskCreatedSuccessfully: "Tâche créée avec succès.",
    taskStatusUpdated: "Statut de la tâche mis à jour.",
    selectedTasksDeleted: "Tâches sélectionnées supprimées avec succès.",
    tasksMarkedDone: "Tâches marquées comme complétées.",
    ticking: "En cours",
    startTracking: "Démarrer le suivi de temps",
    stopTimer: "Arrêter le minuteur",
    manualTimeLog: "Saisir une feuille de temps manuelle",
    minutes: "Minutes",
    whatWork: "Sur quoi avez-vous travaillé ?",
    logTimeSheet: "Enregistrer la Session",
    timeHistory: "Historique des feuilles de temps",
    noTimeHistory: "Aucun journal de suivi de temps enregistré pour cette tâche.",
    sessionSummary: "Résumé de la Session",
    stopAndLog: "Arrêter & Enregistrer",
    uploadFiles: "Transférer des Fichiers",
    dragDropFiles: "Glissez-déposez les fichiers ici",
    orBrowse: "ou parcourez pour transférer",
    fileTypesSupported: "Tous les types de fichiers sont supportés (Max 100 Mo)",
    searchFiles: "Rechercher des fichiers...",
    fileDetails: "Détails du Fichier",
    fileType: "Type",
    fileSize: "Taille",
    uploadedBy: "Transféré Par",
    openMetadata: "Ouvrir la Page des Métadonnées",
    editFile: "Modifier le Fichier",
    project: "Projet",
    fileSelect: "Fichier",
    renameFile: "Renommer le Fichier (Optionnel)",
    descriptionOptional: "Description (Optionnel)",
    fileConflict: "Un fichier avec ce nom existe déjà.",
    uploadAsNewVersion: "Transférer comme nouvelle version (incrémenter la version)",
    overwriteExisting: "Écraser/remplacer l'entrée de fichier existante",
    upload: "Transférer",
    fileUploadedSuccessfully: "Fichier transféré avec succès.",
    fileDeletedSuccessfully: "Fichier supprimé avec succès.",
    deleteFileTitle: "Supprimer le Fichier ?",
    deleteFileDesc: "Êtes-vous sûr de vouloir supprimer définitivement ce fichier ? Cette action est destructive et irréversible.",
    exportGstr1: "Exporter GSTR-1",
    allInvoices: "Toutes les Factures",
    recurringSubscriptions: "Abonnements Récurrents",
    totalBilled: "Total Facturé",
    choosePaymentMethod: "Choisir la méthode de paiement",
    securingRazorpay: "Sécurisé par Razorpay (Mode Mock)",
    downloadPdf: "Télécharger le PDF",
    gstr1Downloaded: "Rapport GSTR-1 téléchargé avec succès.",
    invoiceSent: "Facture envoyée avec succès.",
    paymentSuccessful: "Paiement Réussi !",
    paymentProcessing: "Traitement du paiement...",
    paymentProcessingDesc: "Communication avec les serveurs de paiement.",
    runTemplate: "Déclencher l'Exécution",
    subscriptionTemplateCreated: "Modèle d'abonnement récurrent créé avec succès.",
    subscriptionTemplateDeleted: "Modèle récurrent supprimé.",
    invoiceGeneratedFromTemplate: "Facture générée avec succès à partir de ce modèle !",
    myPortal: "Mon Portail",
    sharedFiles: "Fichiers Partagés",
    myInvoices: "Mes Factures",
    myProjects: "Mes Projets",
    history: "Historique",
    allCaughtUp: "Tout est à jour ! Aucune approbation en attente.",
    requestChanges: "Demander des Modifications",
    feedbackLabel: "Retour Client",
    digitallySigned: "Signé Numériquement & Vérifié",
    timestamp: "Horodatage",
    respondToApproval: "Répondre à l'Approbation",
    approveAndSign: "Approuver & Signer",
    eSignatureVerification: "Vérification de la Signature Électronique",
    typeSignature: "Saisir la Signature",
    sealStamp: "Sceau de Signature",
    typeName: "Saisissez votre Nom Complet",
    signatureStyle: "Style de Signature",
    consentText: "J'accepte que cette signature soit une répresentation valide et juridiquement contraignante de mon approbation, de ma signature électronique et de mon consentement.",
    whyRevisionsNeeded: "Pourquoi des révisions sont-elles nécessaires ?",
    submitRevisionRequest: "Soumettre la Demande de Révision",
    assetApprovedAndSigned: "Actif approuvé et signé avec succès.",
    revisionRequested: "Révision demandée.",
    filesAcrossProjects: "fichiers dans tous les projets",
    pleaseSelectFileAndProject: "Veuillez sélectionner un fichier et un projet à transférer.",
    fileRenamedSuccessfully: "Fichier renommé avec succès.",
    file: "Fichier",
    version: "Version",
    downloads: "Téléchargements",
    download: "Télécharger",
    noFilesFound: "Aucun fichier trouvé",
    noFilesFoundDesc: "Transférez votre premier fichier ou ajustez votre recherche.",
    leaveEmptyOriginalName: "Laisser vide pour utiliser le nom d'origine",
    addBriefDescription: "Ajoutez une brève description du fichier...",
    fileMetadata: "Métadonnées du fichier",
    fileNotFound: "Fichier non trouvé",
    fileNotFoundDesc: "Le fichier demandé n'a pas pu être trouvé ou a été supprimé.",
    fileMetadataDesc: "Métadonnées et paramètres détaillés du fichier en lecture seule",
    properties: "Propriétés",
    uploadDate: "Date de téléchargement",
    projectReference: "Référence du projet",
    downloadFileRaw: "Télécharger le fichier brut",
    noDescriptionProvided: "Aucune description fournie pour ce fichier.",
    storageKey: "Clé de stockage",
    backToFiles: "Retour aux Fichiers",
    recurringInvoices: "Factures récurrentes",
    invoicesCount: "factures",
    recurringActiveCount: "abonnements récurrents actifs",
    awaitingPayment: "En attente de paiement",
    transactionHistory: "Historique des transactions",
    noTransactionsYet: "Aucune transaction pour le moment.",
    transaction: "Transaction",
    method: "Méthode",
    completePayment: "Compléter le paiement",
    paying: "Paiement en cours",
    pleaseWaitDoNotClose: "Veuillez patienter, ne fermez pas cette fenêtre.",
    paymentReceiptGenerated: "Un reçu simulé a été généré.",
    done: "Terminé",
    createSubscriptionTemplate: "Créer un modèle d'abonnement",
    billingFrequency: "Fréquence de facturation",
    firstBillingDate: "Première date de facturation",
    gstTaxRate: "Taux de taxe GST (%)",
    discountType: "Type de remise",
    discountValue: "Valeur de la remise",
    lineItems: "Lignes de facture",
    addItem: "+ Ajouter un élément",
    notesPrintedInvoice: "Notes (imprimées sur la facture générée)",
    notesPlaceholderSubscription: "Ex. Conditions d'abonnement, informations de facturation...",
    pricingCalculationsPreview: "Aperçu des calculs de tarification",
    totalAmount: "Montant total",
    saveTemplate: "Enregistrer le modèle",
    weekly: "Hebdomadaire",
    monthly: "Mensuel",
    quarterly: "Trimestriel",
    percentage: "Pourcentage (%)",
    flatAmount: "Montant fixe",
    accountHolder: "Titulaire du compte",
    bankName: "Nom de la banque",
    accountNumber: "Numéro de compte",
    ifscCode: "Code IFSC",
    upiId: "ID UPI",
    scanToPayUPI: "Scanner pour payer par UPI",
    scanUsingUpiApps: "Scannez avec BHIM, GPay, PhonePe ou Paytm",
    pay: "Payer",
    close: "Fermer",
    stripeCardCheckout: "Paiement par carte Stripe",
    stripeDesc: "Visa, Mastercard, AMEX, Apple Pay",
    paypalCheckout: "Paiement par PayPal",
    paypalDesc: "Payer via le solde ou le compte PayPal",
    wiseTransfer: "Transfert direct Wise",
    wiseDesc: "Simuler un virement bancaire international direct",
    upiDesc: "Google Pay, PhonePe, Paytm",
    cardDesc: "Visa, Mastercard, RuPay",
    netbankingDesc: "Toutes les banques principales",
    creditDebitCard: "Carte de crédit / débit",
    netBanking: "Banque en ligne",
    payNow: "Payer maintenant",
    sendInvoice: "Envoyer la facture",
    taxRate: "Taux de taxe",
    zeroRatedGst: "GST à taux zéro",
    cgst: "CGST",
    sgst: "SGST",
    igst: "IGST",
    rcmWarning: "GST payable sous autoliquidation (RCM). La taxe n'est PAS ajoutée au total de la facture.",
    roundingOff: "Arrondi",
    totalExclGst: "Total (Hors GST)",
    totalInvoiceValue: "Valeur totale de la facture",
    tdsWithheld: "TDS retenu",
    netPayableDue: "Net à payer / dû",
    bankTransferDetails: "Détails du virement bancaire",
    placeOfSupply: "Lieu de livraison",
    dateFilter: "Date",
    today: "Aujourd'hui",
    thisWeek: "Cette semaine",
    thisMonth: "Ce mois-ci",
    thisYear: "Cette année",
    customRange: "Période personnalisée",
    from: "de",
    to: "à",
    overdue: "Impayée",
    sent: "Envoyée",
    paid: "Payée",
    agencyProfile: "Profil de l'agence",
    emailSettings: "Paramètres d'e-mail",
    notificationPreferences: "Préférences de notifications",
    securitySettings: "Paramètres de sécurité",
    brandingConfiguration: "Configuration de la marque",
    settingsDescZenithOS: "Gérez votre configuration ZenithOS",
    companyLogo: "Logo de l'entreprise",
    agencyName: "Nom de l'agence",
    website: "Site web",
    contactEmail: "E-mail de contact",
    gstNumber: "Numéro GST",
    saveChanges: "Enregistrer les modifications",
    emailProvider: "Fournisseur d'e-mails",
    poweredBy: "Propulsé par",
    senderName: "Nom de l'expéditeur",
    senderEmail: "E-mail de l'expéditeur",
    automatedEmails: "E-mails automatisés",
    welcomeEmailClient: "E-mail de bienvenue lors de la création du client",
    approvalRequestNotif: "Notifications de demande d'approbation",
    invoiceDeliveryEmails: "E-mails de livraison de factures",
    paymentReceiptEmails: "E-mails de reçu de paiement",
    deadlineReminders: "Rappels de date limite",
    saveSettings: "Enregistrer les paramètres",
    newClientAdded: "Nouveau client ajouté",
    newClientAddedDesc: "Lorsqu'un nouveau client est créé",
    projectAssignedYou: "Projet qui vous est assigné",
    projectAssignedYouDesc: "Lorsque vous êtes ajouté à un projet",
    approvalReceived: "Approbation reçue",
    approvalReceivedDesc: "Lorsqu'un client répond à une demande d'approbation",
    paymentReceived: "Paiement reçu",
    paymentReceivedDesc: "Lorsqu'une facture est payée",
    deadlineApproaching: "Échéance proche",
    deadlineApproachingDesc: "3 jours avant l'échéance du projet",
    invoiceOverdue: "Facture impayée",
    invoiceOverdueDesc: "Lorsqu'une facture dépasse sa date d'échéance",
    savePreferences: "Enregistrer les préférences",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    confirmNewPassword: "Confirmer le nouveau mot de passe",
    sessionManagement: "Gestion des sessions",
    sessionManagementDesc: "Les jetons JWT expirent après 7 jours. Les jetons de rafraîchissement sont valides pendant 30 jours.",
    loggedOutInactivity: "Vous avez été déconnecté en raison de votre inactivité.",
    updatePassword: "Mettre à jour le mot de passe",
    agencyBrandName: "Nom de l'agence/marque",
    brandAccentTheme: "Thème de couleur de la marque",
    brandLogoUrl: "URL du logo de la marque",
    invoiceFooterText: "Texte de pied de page de facture",
    saveBranding: "Enregistrer la marque",
    orangeDefault: "Orange (Par défaut)",
    blueAccent: "Bleu",
    emeraldAccent: "Émaude",
    indigoAccent: "Indigo",
    violetAccent: "Violet",
    welcomeBack: "Bon retour",
    approvalsWaiting: "approbations en attente",
    invoicesOutstanding: "factures impayées",
    completedTasksOf: "tâches effectuées",
    pending: "En attente",
    signatureStylePreview: "Aperçu du style",
    liveSignaturePreview: "Aperçu de la signature en direct",
    initialsPlaceholder: "Initiales (max 3 lettres)",
    liveStampPreview: "Aperçu du tampon en direct",
    commentNoteOptional: "Commentaire/Note (optionnel)",
    addCommentNotePlaceholder: "Ajoutez un commentaire ou une note...",
    goBack: "Retourner",
    signApprove: "Signer & approuver",
    specifyRevisionsRequired: "Spécifiez exactement les modifications requises...",
    noInvoices: "Aucune facture",
    noInvoicesFoundAccount: "Aucune facture trouvée pour votre compte.",
    createFirstInvoice: "Créez votre première facture à envoyer aux clients.",
    client: "Client",
    inclTax: "taxes incl.",
    nextBillingDate: "Prochaine date de facturation",
    invoiceDetails: "Détails de la facture",
    taxableValue: "Valeur imposable",
    orderId: "ID de commande",
    paymentReceivedSuccess: "reçu avec succès.",
    transactionsRecorded: "transactions enregistrées",
    totalCollected: "Total Encaissé",
    pendingInvoices: "Factures en Attente",
    failed: "Échoué",
    partial: "Partiel",
    received: "reçu",
    inApp: "Dans l'application",
    security: "Sécurité",
    clientPortalWelcomeMessage: "Message de bienvenue du portail client",
    brandingSaved: "Configurations de marque enregistrées et appliquées avec succès !",
    youHave: "Vous avez",
    and: "et",
    of: "sur",
    approve: "Approuver",
    noCompletedApprovalsYet: "Aucune approbation complétée pour le moment.",
    noSharedFiles: "Aucun fichier partagé avec vous pour le moment.",
    action: "Action",
    receipt: "Reçu",
    pdfSimulated: "La génération de PDF est simulée pour cet environnement.",
    assetForReview: "Actif pour examen",
    selectResponseChoice: "Veuillez sélectionner votre choix de réponse ci-dessous :",
    simulatePayment: "Simuler le paiement",
    hsnSac: "HSN/SAC",
    qty: "Qté",
    flat: "Forfait",
    lutNo: "N° de LUT",
    invoice: "Facture",
    agreeToTermsError: "Vous devez accepter les conditions juridiquement contraignantes.",
    typeSignatureError: "Veuillez saisir votre nom pour la signature.",
    stampInitialsError: "Veuillez saisir vos initiales pour le tampon."
  },
}

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('zenithos_language')
    return (saved as Language) || 'en'
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('zenithos_language', lang)
  }

  const t = (key: string): string => {
    const translation = translations[language]?.[key] || translations['en']?.[key]
    return translation || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
